### ISSUE TITLE
Plugin & Test initial infrastructure

### ISSUE THREAD

**Issue by PeterPetrik** [nens/threedi-api-qgis-client#1]
- [ ] browse API/swagger and test the credentials and responses
- [ ] create framework/python module for API calls based on QT networking 
- [ ] create infrastructure for testing of the QT network based module (testing server with some hardcoded responses)
- [ ] setup automatic travis tests infrastructure
- [ ] create QGIS plugin initial structure 

estimate 4 days

**Comment by DamnBack** [comment]
Done.
