### ISSUE TITLE
adding geojsons [enhancement]

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#101]
* threedi-api-qgis-client version:
* Python version:
* Operating System:

### Description
when loading a model from the web I would like to add the option of downloading the geojsons from the API.
Downloading is only required when according to checksums the geojsons are different than the ones already downloaded/ 

workflow:
users gets a list of potential downloads
indicates a folder where to download the geojsons to
clicks download

for now the only supported downloads are:
- cells
- breaches

by default all can be 'checked' 

/threedimodels/{id}/geojson/cells/download/
/threedimodels/{id}/geojson/breaches/download/

**Comment by DamnBack** [comment]
Caching of the breaches and cells done.

**Comment by Jonasvsl** [comment]
@DamnBack 
in my version the breaches and cells are not automatically added to the mapcanvas

breaches are added after entering the breaches window in the simulation wizard but when the wizard windows is active it is impossible to zoom and pan in the map canvas. like this the current workflow is: a user has to start a simulation, select breaches. 
 then it loads the geojson. then the user has to quit the wizard, look for the breach, and then start the wizard again from scratch?

**Comment by leendertvanwolfswinkel** [comment]
@Jonasvsl I am closing this issue, I think this has already been implemented. If you select a breach from the list, the map canvas pans to that location and the selected breach is highlighted
