### ISSUE TITLE
Login: can I store my credentials somehow?

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#106]
* threedi-api-qgis-client version:
* Python version:
* Operating System:

### Description

Users now have to type credentials. Is there a secure way to store the credentials for them?

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by leendertvanwolfswinkel** [comment]
duplicate of #116
