### ISSUE TITLE
Smarter use of organisations in New schematisation and Billing goes to

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#107]
There are two places where users select an organisation:

**New schematisation wizard**
Please save the selected organisation in the QGIS settings, and attempt to switch to that organisation when populating the organisation selector comboboxes. As a fallback, go to the first org in the list.

**Simulation wizard ("Billing goes to...")**
When populating the organisation selector combobox, switch to the organisation the `threedimodel` (or its `schematisation`) belongs to.

**Comment by leendertvanwolfswinkel** [comment]
@ldebek I realise the way I phrased the second point (for the Simulation Wizard) was not accurate. What I mean is, When a 3Di model is chosen in the top list widget, the "Billing goes to" combobox should switch to the organisation that owns the model's schematisation. 

<img width="1220" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkI4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5dd4fcdd3355ff86a3eee2e5353100e88758dbd8/image.png" alt="image.png" />

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Requested changes applied.
