### ISSUE TITLE
model name instead of model_ini in panel

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#108]
* threedi-api-qgis-client version:
* Python version:
* Operating System:

### Description

In 'Database' there is a .ini file. The user never sees this .ini file. Maybe split it in schematisation file and scenario name.
It appears that model_ini is being shown in the panel instead of model name, 

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by leendertvanwolfswinkel** [comment]
![image](https://user-images.githubusercontent.com/26224299/125311406-ad951d00-e333-11eb-8699-fe1e0870de4d.png)
