### ISSUE TITLE
Options move around when selecting other boxes (for example selection of 'damage estimation')

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#109]
* threedi-api-qgis-client version:
* Python version:
* Operating System:

### Description

Options move around when selecting other boxes (for example selection of 'damage estimation')

Can we set this in some way? It does work but is not a nice look & feel

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by leendertvanwolfswinkel** [comment]
Fixed with #432
