### ISSUE TITLE
add radar rain to precipitation options

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#111]
* threedi-api-qgis-client version:
* Python version:
* Operating System:

### Description
For users in the Netherlands (and potentially other countries) it is possible to use radar rain in calculations:
It is simular to the constant one, except that instead of constant we call it radar:

![image](https://user-images.githubusercontent.com/1453159/88031861-7c797680-cb3d-11ea-9e7e-fe396826ca56.png)

radar rain needs a start and end time. proposition is to use the duration of the simulation datetimes, and use the gui for users to set a potential offset when using the radar rain. an intensity preview is not available 

the reference uuid to be used in the API endpoint is: d6c2347d-7bd1-4d9d-a1f6-b342c865516f
this endpoint: /simulations/{simulation_pk}/events/rain/rasters/lizard/

The dropdown menu should be called 'Radar - NL Only' 
The addition is to avoid that users from outside the Netherlands are going to mistakenly try this

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by DamnBack** [comment]
New precipitation type added, but cannot test it, because API says that I don't have access to the Lizard API. I'm getting message like this: `Error: ["Unauthorized to access the Lizard API"]`.
