### ISSUE TITLE
store username / pw in qgis password manager

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#116]
* threedi-api-qgis-client version:
* Python version:
* Operating System:

### Description

I would love to be able to store my username/password in the QGIS password manager

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by leendertvanwolfswinkel** [comment]
Postponed to wait for new login method with api key
