### ISSUE TITLE
start_datetime always set to current start_datetime instead of what users gives as input

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#118]
* threedi-api-qgis-client version: 2.1.1
* Python version:
* Operating System:

### Description

As input I gave different dates to start the simulation with:\
1-1-2020
and 10-1-2020
but in all cases the simulation started with this:
start_datetime": "2020-10-12T09:39:36Z",

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by DamnBack** [comment]
Estimate in days: 0.25
