### ISSUE TITLE
time series add interpolation method

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#119]
* threedi-api-qgis-client version:
* Python version:
* Operating System:

### Description

timeseries have the option to interpolate
it's a boolean field, yes/no
add as an extra selection to timeseries lateral page

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by DamnBack** [comment]
Estimate in days: 0.5

**Comment by Jonasvsl** [comment]
duplicate #126
