### ISSUE TITLE
Add wind to the api wizard 

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#120]
wind can either constant or time series

![image](https://user-images.githubusercontent.com/1453159/96469595-ae2dd680-122d-11eb-8a0e-e36c1e484caf.png)

Design link for wireframe review:
https://xd.adobe.com/view/e3b00c01-f856-4191-b40d-9eefc4447059-b6e3/

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by lexvand** [comment]
@LirryPinter Could you have a look at this one? Do you enough info to make a design?

**Comment by LirryPinter** [comment]
@lexvand @Jonasvsl 

I have enough information, can start on this.

**Comment by Jonasvsl** [comment]
@LirryPinter 
One addition there is also an initial condition: the wind drag coefficient. can vary between 0 and 100. is constant for the whole simulation

**Comment by LirryPinter** [comment]
@Jonasvsl 
Can you explain what that is exactly? Is this a new functionality?

**Comment by Jonasvsl** [comment]
this is part of the wind implementation. let's discuss in a (short) meeting

**Comment by LirryPinter** [comment]
After talking with nici and jonas:

Windsnelheden worden atijd op 10meter hoogte gegeven.
Advanced:
Drag cofficient instellen met default.
Is de default over verschillende modellen --> 0.005
https://docs.3di.lizard.net/b_wind.html

_Constant_
**Windsnelheid** --> km/h (m/s) EN beaufort
**Offset** 
**Duration**
**Direction**
**Drag coefficient**

Bij _tijdseries_ komen er:
Interpolatie voor **speed** en **direction** bij
**Drag coefficient**

**Comment by LirryPinter** [comment]
Wind bij start scherm voor keuzes in API firestarter

**Comment by LirryPinter** [comment]
Updated the flowchart on the drive, now contains wind.

**Comment by Jonasvsl** [comment]
for the wind I think we need an explainer on the angles. Maybe something similar as we have in the live site. I have problems understanding which wind direction 90 degrees is

**Comment by Jonasvsl** [comment]
could also be something like this to show the user what the angle means:
https://stackoverflow.com/questions/7490660/converting-wind-direction-in-angles-to-text-words

**Comment by LirryPinter** [comment]
@Jonasvsl 

Updated design: let me know what you think

**Comment by Jonasvsl** [comment]
@LirryPinter 
Looks good! 
I have my some doubts on how much work it is for lutra to implement the arrow as you show it. But we can discuss this with them. I would like to be flexible and perhaps change to an implementation as I mentioned above if that would take way less time.

Btw. You misspelled drag coefficient, please change so there is no confusion

**Comment by DamnBack** [comment]
Estimate in days: 2-3 days

**Comment by Jonasvsl** [comment]
here in dutch an explanation on wind direction:
https://www.meteo-gouda.nl/verwachting-windkracht.html

**Comment by Jonasvsl** [comment]
I am under the impression the angles for wind as used in the plugin should be exactly reversed. I'm checking with backend team on that

**Comment by Jonasvsl** [comment]
Yes, the problem with wind is that the standards in this field are exactly opposite of what one usually expects. Here some examples how the angles should be:
![image](https://user-images.githubusercontent.com/1453159/104308318-c03bb000-54d0-11eb-9b75-091858271b98.png)

![image](https://user-images.githubusercontent.com/1453159/104308343-cb8edb80-54d0-11eb-89dd-05b1deedc5df.png)

![image](https://user-images.githubusercontent.com/1453159/104308361-d2b5e980-54d0-11eb-8ab8-beb8f2092ede.png)

![image](https://user-images.githubusercontent.com/1453159/104308386-da758e00-54d0-11eb-9422-77fa1cd18408.png)

**Comment by DamnBack** [comment]
Wind direction should work correctly now.
