### ISSUE TITLE
use lateral file upload instead of seperate api calls

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#121]
we have created a new endpoint thus minimizing the need for seperate api calls per lateral

![image](https://user-images.githubusercontent.com/1453159/96469846-f77e2600-122d-11eb-94ae-ace479c03749.png)

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by Jonasvsl** [comment]
for better reference here the swagger file. 
[swagger (1).zip](https://github.com/nens/threedi-api-qgis-client/files/5443617/swagger.1.zip)

**Comment by DamnBack** [comment]
Estimate in days: 0.25
