### ISSUE TITLE
upload netcdf rainfall file option 

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#122]
add upload rainfall file upload uption to the rainfall screen

![image](https://user-images.githubusercontent.com/1453159/96470119-3ca25800-122e-11eb-9ced-eb14ccf3abcb.png)

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by DamnBack** [comment]
Estimate in days: 0.5

**Comment by DamnBack** [comment]
@Jonasvsl Could you add example file for this file and the screenshot showing where you would like to add this option? Should it be upload button?

**Comment by Jonasvsl** [comment]
![image](https://user-images.githubusercontent.com/1453159/98697007-b8e31380-2374-11eb-8cac-ece150cb650c.png)
this is the logical place to me, in the custom screen. so a user can choose to either upload a csv or a netcdf

**Comment by Jonasvsl** [comment]
example file is coming, I have a request pending

**Comment by Jonasvsl** [comment]
I am still testing, it takes a bit longer because I have problems analyzing the results. 
One thing I noticed is a typo:
![image](https://user-images.githubusercontent.com/1453159/99409079-47194580-28f1-11eb-9fc8-58f4ec64794e.png)
