### ISSUE TITLE
Use of tags to start up simulations

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#124]
* threedi-api-qgis-client version:
* Python version:
* Operating System:

starting up a simulation now asks for a name
optionally users can also add tags. this is something the api supports, the plugin yet doesn't.

--> add tags to the screen of start up

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by DamnBack** [comment]
Estimate in days: 0.5
