### ISSUE TITLE
Search through breaches list

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#125]
discusses with Lukasz before, I think on slack.

the current selection of breach is by breach id. if there are more than a 100 breaches this list is hard to scroll. 

required: 
dropdown with text search or similar.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by Jonasvsl** [comment]
see also ticket #98

**Comment by DamnBack** [comment]
Estimate in days: 1.5
