### ISSUE TITLE
add interpolate flag to time series

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#126]
the api supports interpolating timeseries (boolean value, default false)

- lateral timeseries
- local rain timeseries
- rain lizard timeseries
- sources sinks timeseries
- sources sinks lizard timeseries
- wind (speed interpolate and direction interpolate)

**Comment by Jonasvsl** [comment]
I can't access the wizard right now, so no screenshots possible, but interpolate needs to be added to the following screens:
- laterals
- rain 

for the rain it is called custom timeseries, users upload a csv. smae for laterals

the other options that are mentioned above are not implemented in the wizard yet so for now please ignore them, apologies for the confusion

**Comment by DamnBack** [comment]
Estimate in days: 1
