### ISSUE TITLE
sources and sinks add to qgis client

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#127]
design required

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by lexvand** [comment]
@LirryPinter Could you have a look at this one? Do you enough info to make a design?

**Comment by LirryPinter** [comment]
From the swagger file i got the following:

Sources and sinks can be

- **Constant, Timeseries or rasters**

- **Timeseries** can come from:
 - Lizard
 - NetCDF
 - Seperate file

- **Rasters** can come from:
 - Lizard
 - NetCDF
 - Seperate file

**Comment by Jonasvsl** [comment]
@LirryPinter do you have a question or was your last comment more a collection of information for yourself?
