### ISSUE TITLE
Paginating issue 

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#128]
* threedi-api-qgis-client version: 2.1.1
* Python version: 
* Operating System: windows

### Description

The current way of requesting the API as the plugin does is not compatible with a new implementation of the backend.

`Pagination🔗
All top-level API resources as well as quite some sub-level resources have support for bulk fetches via "list" API methods. That means that you can list simulation or threedimodel resources in bulk. List API methods take an offset and limit parameter that can be used to customize the pagination response.
Parameter 	type 	Description
limit [optional] 	integer 	Limit on the number of entries to be returned, between 1 and 250. Default is 10.
offset [optional] 	integer 	Start returning objects from this cursor position on. Default is 1.
The top-level keys of response body are
{
  "count":    # total number of resources
  "next":     # url the next page
  "previous": # url the previous page
  "results":  # results for this page
}

`
This function:

`if response_count > self.FETCH_LIMIT:
            response = api.revisions_list(limit=response_count)`

Fetches the limit. Currently that can be 50.000, however by default the server returns at max 250 responses.

so if there are more than this in the repo the following error occurs:

![image](https://user-images.githubusercontent.com/1453159/97577346-9b668f00-19ef-11eb-8149-68b05d2883b0.png)

This means that the implementation of the following api calls needs to be changed:

- lists of simulations
- repositories
- 3di models
- simulation results
- simulation downloads
- breaches
- waterlevels
- saved states
- revisions_list

**Comment by Jonasvsl** [comment]
stack trace in qgis:

An error has occurred while executing Python code: 

KeyError: '4d7e6703290a75a9a7a84f802e6ac86b050bbbaf' 
Traceback (most recent call last):
  File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\testwd/python/plugins\threedi_api_qgis_client\widgets\threedi_api_qgis_client_dockwidget.py", line 124, in change_model
    revision = self.log_in_dlg.revisions[self.current_model.revision_hash]
KeyError: '4d7e6703290a75a9a7a84f802e6ac86b050bbbaf'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.10.9-A Coruña A Coruña, bf47e9d3e1 

Python Path:
C:/PROGRA~1/3DIMOD~1.10/apps/qgis-ltr/./python
C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\testwd/python
C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\testwd/python/plugins
C:/PROGRA~1/3DIMOD~1.10/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\3DIMOD~1.10\apps\Python37
C:\PROGRA~1\3DIMOD~1.10\apps\Python37\Scripts
C:\PROGRA~1\3DIMOD~1.10\bin\python37.zip
C:\PROGRA~1\3DIMOD~1.10\apps\Python37\DLLs
C:\PROGRA~1\3DIMOD~1.10\apps\Python37\lib
C:\PROGRA~1\3DIMOD~1.10\bin
C:\PROGRA~1\3DIMOD~1.10\apps\Python37\lib\site-packages
C:\PROGRA~1\3DIMOD~1.10\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\3DIMOD~1.10\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\3DIMOD~1.10\apps\Python37\lib\site-packages\Pythonwin
C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\testwd/python
C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\profiles\testwd\python\plugins\threedi_api_qgis_client\deps\PyJWT-1.7.1-py2.py3-none-any.whl
C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\profiles\testwd\python\plugins\threedi_api_qgis_client\deps\threedi_api_client-3.0.6-py2.py3-none-any.whl

**Comment by Jonasvsl** [comment]
this is the message that the users see:
`2020-10-29T14:24:25     WARNING    Python error : An error has occurred while executing Python code: See message log (Python Error) for more details.`

**Comment by DamnBack** [comment]
Should be fixed now.

**Comment by Jonasvsl** [comment]
@DamnBack 
Can you add spent time to this ticket?

**Comment by DamnBack** [comment]
Time spent (fixing bug + releasing new plugin version): 5 hours.
