### ISSUE TITLE
[waiting for backend] Throttling

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#133]
* threedi-api-qgis-client version:
* Python version:
* Operating System:
The API can start to throttle users when they interact too much. Currently what happens is that a user follows all the steps in the wizard, only to get this error:

Error: {"detail": "Request was throttled. Expected available in 6 seconds."}' .
then nothing happens and the user has to wait 6 seconds (in this example) before trying again.

Is there a way to hold the request until throttling has finished and then push the call again? Within certain limits of course

**Comment by DamnBack** [comment]
@Jonasvsl There are 3 approaches that I can see for dealing with that issue.
1. Just use a simulation templates and run it again (estimation: **0 days** 😃)
2. Caching and parsing throttling response and waiting given number of seconds to retry request. This one will block plugin na QGIS interface until request will be retried. (estimation: **0.5 days**)
3. Caching and parsing throttling response and waiting given number of seconds to retry request. This time however request will be moved to separate thread, so user interface won't be blocked. This would be probably most elegant approach, but would need a bit of refactoring the running simulation mechanism.  (estimation: **2 - 3 days**)

**Comment by Jonasvsl** [comment]
4. Check on the server whether throttling is occuring. if that happens then save to template with a message to user to try again in xx minutes

**Comment by leendertvanwolfswinkel** [comment]
Fixed in v 2.4.1
