### ISSUE TITLE
Simulation wizard: support 1D initial water levels Topdesk 2009 0023

### ISSUE THREAD

**Issue by lisannewapstra** [nens/threedi-api-qgis-client#137]
Topdesk 2009 0023

This has been implemented in the API, but not yet in the MI

Implementation: 
- User uploads a CSV file with two columns: id and value. ID is the calculation node id, value is the initial water level
- Simulation wizard converts it to JSON and uploads it, **replacing existing 1D initial water levels**

See the example script & data I shared with you on Teams @hoanphungt

**Comment by leendertvanwolfswinkel** [comment]
Doesn't sound like a super common use case and complicated to implement in a intuitive, user friendly way, adding low-prio label

**Comment by leendertvanwolfswinkel** [comment]
@hoanphungt it works very well

One additional request (probably applies to all CSV processing): can you make it handle empty values? I have a csv file with some missing values, which causes a Python error. Please give the following feedback to the user: "The CSV file has some missing values. Please remove those lines or fill in a value and try again."

To reproduce (on staging): Hekerbeek #1 with this CSV file:

**Comment by leendertvanwolfswinkel** [comment]
@hoanphungt it works great, please merge :)
