### ISSUE TITLE
Put wizard in processing toolbox

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#138]
We have discussed this before but I would like to know what is the estimate to put the wizard in the processing toolbar of qgis. I’m mostly interested in the batch functionality that that enables. 
Or are there easier ways to put the wizard in a batch script or similar?

**Comment by DamnBack** [comment]
This task will need moving part of the logic from wizard to standalone functions that can be used by both - wizard an processing toolbox.
Estimate in days: 8 - 10 days.

**Comment by leendertvanwolfswinkel** [comment]
@Jonasvsl is this still relevant now that running multiple simulations is already an option in the wizard itself?

**Comment by leendertvanwolfswinkel** [comment]
The wizard has become so complicated by now that I do no longer see this as a viable option
