### ISSUE TITLE
watch running simulations in QGIS API client

### ISSUE THREAD

**Issue by lisannewapstra** [nens/threedi-api-qgis-client#139]
Topdesk 2010 0027 Running simulations bekijken in QGIS 3Di API Client

* QGIS 3Di API Client Plugin

### Description
Leendert van Wolfswinkel October 5, 2020 07:16 PM
For whom do you want to create a ticket?
- For myself

Describe your issue:
- If you open the api client just to see which simulations are running, you need to load a model via start. it would be handy if this option as available from the start
@LirryPinter see feedback Leendert on the flow of the UI in qgis api client let's discuss

**Comment by leendertvanwolfswinkel** [comment]
implemented in 2.99.0
