### ISSUE TITLE
Can you configure the base URL of the API to use in the modeler interface?

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#141]
is it possble to make this configurable, like in settings?
it is changeable in the code by replace in files but that's not really user friendly. 

we are going to work with different urls for different countries, so users should be able to set the base url (api.3di.live ) and replace it with some other url. and save that setting as well

**Comment by DamnBack** [comment]
Estimate in days: 1 day.

**Comment by Jonasvsl** [comment]
Correct implementation, however the active button after typing is 'use default' instead of 'save'. Please change that into 'save' as active button in that window.

**Comment by DamnBack** [comment]
'Save' button should be active first now.
