### ISSUE TITLE
add extra file upload option to laterals screen

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#142]
users can have two types of laterals:
'normal laterals'
and dwf inflow laterals.

the current screen only takes normal laterals into account. we need an extra upload option for dwf_flow laterals. for this one it is not possible to change individual laterals.

**Comment by leendertvanwolfswinkel** [comment]
I'll soon add a proposal in #161 to cover this use case in a slightly different way
