### ISSUE TITLE
2108 0050 Rain intensity preview is not showing what it should 

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#144]
* threedi-api-qgis-client version: 2.2.0
* Python version:
* Operating System:
Rain intensity preview is not showing what it should:

![image](https://user-images.githubusercontent.com/1453159/102184047-1ce68380-3eaf-11eb-89f7-ceeec0deb708.png)

0,0.18
15,0.18
30,0.18
45,0.18
1440,0.18

What would be expected is that the amount of rain is going to be for the next timestep. the graph is not showing that

**Comment by leendertvanwolfswinkel** [comment]
This seems to be caused by a non-equidistant time step in the csv, which is no longer possible (see #362)
