### ISSUE TITLE
QGIS api client produces too many api calls on start up of the plugin and causes the API to start throttling 

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#151]
* threedi-api-qgis-client version: 2.4.0.
* Python version:
* Operating System: 

### Description

This piece of code:
https://github.com/nens/threedi-api-qgis-client/blob/e7859b7b9dd4fc84adfcc8dbd713a9efc6a8e76b/threedi_api_qgis_client/workers.py#L37
we assume is being used to trigger the progress bars. but these should all come straight from the websocket

The code in combination with this piece:
![image](https://user-images.githubusercontent.com/1453159/112655805-10c87580-8e51-11eb-854a-e4a8f302ae48.png)

means that to show the progress bar for users ALL simulations are being looped. After 120 per minute throttling kicks in. Which will start to happen to more and more users.

In the past months we have also some code that can help with this:
https://github.com/nens/threedi-cmd/blob/4c057726fb57de2ad5c74ac55ca2bfc38f51d7f9/threedi_cmd/models/monitor.py

I propose to pick up this ticket in combination with a small meeting with the 3Di techlead. I think within half an hour it is clear what needs to be done. 
 

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by reinout** [comment]
@jpprins1 has a better URL we can call (says @Jonasvsl)

**Comment by jpprins1** [comment]
Overview of last statuses (of all simulations):
https://api.3di.live/v3.0/statuses/

**Comment by reinout** [comment]
Bit of grepping in the haproxy logfile shows this behaviour:

    GET /v3.0/organisations/?limit=250
    GET /v3.0/repositories/?limit=250
    GET /v3.0/simulations/?created__date__gt=2021-05-04&limit=250
    GET /v3.0/revisions/?limit=250
    GET /v3.0/simulations/21116/status/?limit=250
    GET /v3.0/simulations/21115/status/?limit=250
    GET /v3.0/simulations/21115/status/?limit=250
    GET /v3.0/simulations/21114/status/?limit=250
    GET /v3.0/simulations/21114/status/?limit=250
    GET /v3.0/simulations/21113/status/?limit=250
    GET /v3.0/simulations/21112/status/?limit=250
    GET /v3.0/simulations/21111/status/?limit=250
    GET /v3.0/simulations/21110/status/?limit=250
    GET /v3.0/simulations/21108/status/?limit=250
    GET /v3.0/simulations/21107/status/?limit=250
    GET /v3.0/simulations/21106/status/?limit=250
    GET /v3.0/simulations/21105/status/?limit=250
    GET /v3.0/simulations/21104/status/?limit=250
    GET /v3.0/simulations/21103/status/?limit=250
    GET /v3.0/simulations/21102/status/?limit=250
    GET /v3.0/simulations/21101/status/?limit=250
    GET /v3.0/simulations/21100/status/?limit=250
    GET /v3.0/simulations/21099/status/?limit=250
    GET /v3.0/simulations/21097/status/?limit=250

And that list of simulations is MUCH longer for some users.

**Comment by reinout** [comment]
2.4.1 is gereleased:
https://plugins.lizard.net/threedi_api_qgis_client.2.4.1.zip

**Comment by reinout** [comment]
.... en hij zit in de modeller interface:
https://docs.3di.live/modeller-interface-downloads/3DiModellerInterface-OSGeo4W-3.16.7-1-Setup-x86_64.exe
