### ISSUE TITLE
Change naming of initial water level inputs

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#166]
1D: Instead of 'Predefined': 'From spatialite'
2D: Instead of initial_waterlevels.msgpack: 'From spatialite / raster'

**Comment by ldebek** [comment]
@leendertvanwolfswinkel After looking at API for fetching initial water level rasters for 2D (for groundwater and saved states as well) it seems that multiple rasters can be returned, so I would stick with current combobox that allows to pick correct file.

**Comment by Patrick-Nijman** [comment]
Our API backend will change the name of  initial_waterlevels.msgpack to resemble the name of the delivered sourcefile so it will be clearer that this is the initial water levels from the source file.
