### ISSUE TITLE
Make lateral file obligatory if laterals are included

### ISSUE THREAD

**Issue by lisannewapstra** [nens/threedi-api-qgis-client#169]
* threedi-api-client version:  2.4.1
* Python version: 3.7.0
* Operating System: Windows
* relating Topdesk ticket: 2107 0180 Bas van Haaren

### Description of the issue
This simulation https://api.3di.live/v3.0/simulations/32088/ remained on progress 0%, 
The simulation could not start, because an empty lateral file was sent to the API. 
What happened? 
Bas checked the laterals in the first screen ('options'), but did not upload a file in the laterals tab. 
![image](https://user-images.githubusercontent.com/33685743/127146647-ef5a0c96-b45a-4550-853a-cb11e79605ed.png)
![image](https://user-images.githubusercontent.com/33685743/127146704-afd42392-431e-40b9-b9b8-3912040fadcf.png)

You can just leave this empty without a warning

### Expected solution 
Raise a warning if there is no file uploaded.

**Comment by leendertvanwolfswinkel** [comment]
@lisannewapstra will be included in upcoming release (~15 feb)
