### ISSUE TITLE
Uploaded file has not been processed error

### ISSUE THREAD

**Issue by Patrick-Nijman** [nens/threedi-api-qgis-client#175]
To reproduce the problem please load the model vossenburchkade (which Jonas provided)

Start a new simulation and tick the box **Include dry weather flow** 

Use the attached CSV file for the values (It's a 24hr inflow)
 
[dwf_inflow_24uur.csv](https://github.com/nens/threedi-api-qgis-client/files/6999796/dwf_inflow_24uur.csv)

When the simulation is added the plugin will give an error: **Uploaded file has not been processed** with the URL

The API has processed the file when we check in the Django link. We think this has to do with the Asynchronous operation. After uploading a reasonable big file the processing will not be available realtime. It will take a couple of seconds to process the file. 

If it's not possible to wait for the result we would suggest checking back 1,2,5,10,etc seconds to see if the processed data is available. Maybe it's possible to connect with the websocket so there is more communication possible. 

This problem also occurs when uploading big file with the include lateral option.

**Comment by Patrick-Nijman** [comment]
After some more testing we found that the time-out setting in the Plugin Settings is just counting to the threshold. I have tested with 
20 sec. (Not processed Error)
40 sec. (Added to queue after 47 secs)
45 sec. (Default) (Added to the queue after 53 secs)
450 sec. (Added to the queue after 8.06 min)

Please look into it and see if you can continue after the processed return from the API

Thanks!

Patrick

**Comment by ldebek** [comment]
Threshold should be now respected.
