### ISSUE TITLE
Disallow opt-out for 'basic processed results' when post-processing in Lizard is chosen

### ISSUE THREAD

**Issue by Patrick-Nijman** [nens/threedi-api-qgis-client#176]
![image](https://user-images.githubusercontent.com/86961942/129747076-8317de6f-6311-47a6-8399-9abc8d9a6895.png)

If Post-Processing in Lizard is ticked and you want to tick Arrival Time Map or Damage Estimation the option **Basic Processed Results** should be enabled as well. It's now possible to tick a box without selecting **Basic Processed Results** this will result in an error after submitting the simulation. The Above screenshot will result in an error.

**Comment by leendertvanwolfswinkel** [comment]
Fixed in #432
