### ISSUE TITLE
design rain should use constant rain  in some cases 

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#177]
The time series endpoint accepts only a max of 300 entries, hence using design rain 14,15,16 will crash.

Explainer:

The area wide rain table (https://github.com/nens/threedi-api-qgis-client/blob/6283a2e910ca559ed5ce7e7da34876494ebb560b/threedi_api_qgis_client/widgets/wizard.py#L74)

looks like this: 
`AREA_WIDE_RAIN = {
    "0": [0.0],
    "1": [0.0],
    "2": [0.0],
    "3": [0.30, 0.60, 0.90, 1.50, 2.10, 2.10, 1.50, 1.20, 1.05, 0.90, 0.75, 0.60, 0.45, 0.30, 0.15],
    "4": [0.15, 0.30, 0.45, 0.60, 0.75, 0.90, 1.05, 1.20, 1.50, 2.10, 2.10, 1.50, 0.90, 0.60, 0.30],
    "5": [0.30, 0.60, 1.50, 2.70, 2.70, 2.10, 1.50, 1.20, 1.05, 0.90, 0.75, 0.60, 0.45, 0.30, 0.15],
    "6": [0.15, 0.30, 0.45, 0.60, 0.75, 0.90, 1.05, 1.20, 1.50, 2.10, 2.70, 2.70, 1.50, 0.60, 0.30],
    "7": [0.6, 1.2, 2.1, 3.3, 3.3, 2.7, 2.1, 1.5, 1.2, 0.9, 0.6, 0.3],
    "8": [0.3, 0.6, 0.9, 1.2, 1.5, 2.1, 2.7, 3.3, 3.3, 2.1, 1.2, 0.6],
    "9": [1.5, 2.7, 4.8, 4.8, 4.2, 3.3, 2.7, 2.1, 1.5, 0.9, 0.6, 0.3],
    "10": [1.8, 3.6, 6.3, 6.3, 5.7, 4.8, 3.6, 2.4, 1.2],
    "11": [5.833333333] * 12,
    "12": [7.5] * 12,
    "13": [6.666666667] * 24,
    "14": [0.208333333] * 576,
    "15": [0.225694444] * 576,
    "16": [0.277777778] * 576,
}`

Number 11 till 16 are sent as time series but are basically constant. They should use the constant endpoint:
![image](https://user-images.githubusercontent.com/1453159/130076598-480e7470-1140-4e94-9114-811e4179575c.png)

The time series endpoint accepts only a max of 300 entries, hence using the 14,15,16 will crash

**Comment by ldebek** [comment]
I've reduced timeseries for 14,15,16 to 300 rows to avoid crashing. Changing it to constant would require bit more work, as there might be needed, some changes in plotting precipitation graph.

**Comment by ldebek** [comment]
@Patrick-Nijman Propposed changes will break graph drawing as they contain timesteps and values while graph uses 1-dimension array with values only. But from your explanation I can suspect that you should get proper results if we make changes as shown below:
    "14": [0.208333333] * 48 + [0.0],
    "15": [0.225694444] * 48 + [0.0],
    "16": [0.277777778] * 48 + [0.0],
