### ISSUE TITLE
Change initial_waterlevels.msgpack in name-of-sourcefile

### ISSUE THREAD

**Issue by Patrick-Nijman** [nens/threedi-api-qgis-client#179]
@Patrick-Nijman commented on [Tue Aug 17 2021](https://github.com/nens/threedi-api/issues/1133)

When there are initial water levels included in a model these initial water levels will be selectable by the user when starting a simulation. If they choose to do so they now can select from a dropdown but there will be the somewhat cryptic name initial_waterlevels.msgpack. If possible change the first part of the filename to the name of the source file so the user understands it's the initial water levels from the current model. 

---

@jpprins1 commented on [Tue Sep 07 2021](https://github.com/nens/threedi-api/issues/1133#issuecomment-914036135)

They need to use the `soure_raster.name` field instead, this is coupled to the source raster used to get compute the aggregations (min/max/avg) which can be added to a simulation as initial waterlevel (2D or groundwater)

**Comment by leendertvanwolfswinkel** [comment]
example: https://api.staging.3di.live/v3/threedimodels/14228/initial_waterlevels/787/
