### ISSUE TITLE
Add discharge coefficients and max breach depth to the breach tab

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#187]
The following API functionalities should be exposed in the GUI:
- discharge coefficient positive
- discharge coefficient negative
- maximum breach depth

**Comment by leendertvanwolfswinkel** [comment]
- Set default for both discharge coefficients to 1
- Maximum breach depth default value: read from potential_breach
- Align widgets
- Make font and font size the same in all widgets (the smaller font sizes should be changed to larger font size)
- While you're at it, please check the font & font size thing for all parts of the simulation wizard. E.g. on the last page, the breach information has a different font I think.

![image](https://user-images.githubusercontent.com/26224299/188127761-557737e0-1b14-45f7-9d5a-0c1f902d597e.png)

**Comment by leendertvanwolfswinkel** [comment]
Almost there...

Maximum breach depth default value is still 0.0. Can you read this from the `potential_breach`?

"Start after" seems to have a smaller font size?

![image](https://user-images.githubusercontent.com/26224299/188669983-66d5c215-d992-44c5-8127-1860f0066dab.png)

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Value should be populated from potential breach already - is there any model that I can use for testing to check what might be wrong?

**Comment by leendertvanwolfswinkel** [comment]
I tested your last commit and it's almost perfect. Setting the correct default for Maximum breach depth is a bit more complicated than I thought before.

- [ ] If there is a breach in the simulation template, use the maximum_breach_depth from that breach (use first breach if there are multiple breaches in the sim template)
- [x] If there is no breach in the simulation template or if the user selects another breach from the dropdown widget, use the maximum_breach_depth from the potential_breach that the user selected

**Comment by leendertvanwolfswinkel** [comment]
For example, this simulation template: `https://api.staging.3di.live/v3/simulation-templates/460/`
refers to a simulation with these events: `https://api.staging.3di.live/v3/simulations/24201/events/`

```
"breach": [
        {
            "url": "https://api.staging.3di.live/v3/simulations/24201/events/breaches/493/",
            "potential_breach": "https://api.staging.3di.live/v3/threedimodels/16319/potentialbreaches/16518/",
            "line_id": 3087,
            "duration_till_max_depth": 1800,
            "maximum_breach_depth": 2.34,
            "levee_material": "sand",
            "initial_width": 24.0,
            "discharge_coefficient_positive": 0.8,
            "discharge_coefficient_negative": 0.63,
            "simulation": "https://api.staging.3di.live/v3/simulations/24201/",
            "offset": 300,
            "id": 493,
            "uid": "0963414c-9cf5-461d-8c53-70643d018122"
        }
    ],
```
So if I load this template in the wizard, I expect the breach properties to be prepopulated as follows:
- "duration_till_max_depth": 1800,
- "maximum_breach_depth": 2.34,
- "initial_width": 24.0,
- "discharge_coefficient_positive": 0.8,
- "discharge_coefficient_negative": 0.63,
- "offset": 300,

This works correctly for all parameters, except `maximum breach depth`, which seems to have taken the original value from the `potential breach`.
![image](https://user-images.githubusercontent.com/26224299/189736648-f674ac13-3a8d-4b18-b845-fd3857436860.png)

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Issue should be fixed now.
