### ISSUE TITLE
New schematisation functionality

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#199]
See functional design document: https://nelenschuurmans-my.sharepoint.com/:w:/g/personal/jonas_vanschrojenstein_nelen-schuurmans_nl/EVF-IDYN2dRJjQKD21RmEK8BI5A2e4awUjuSlKuOXjI_CA?e=LD7HNn

**Comment by ldebek** [comment]
Loading spatialite model via 3Di Toolbox can't be done in an elgant way, so this usability was skipped for a time beign. New shematisation model can still be loaded via `Select 3Di results` tool from  3Di Toolbox plugin.

**Comment by leendertvanwolfswinkel** [comment]
For further improvements separate tickets will be made
