### ISSUE TITLE
Already running simulations are not fetched when logging in

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#201]
* threedi-api-qgis-client version: 2.99.0

After clicking on Simulate and logging in, I would like to see a list of running simulations. It should include simulations that were started before I logged in, for all organisations that I have access rights to

**Comment by leendertvanwolfswinkel** [comment]
caused by a backend issue on staging

**Comment by Jonasvsl** [comment]
@leendertvanwolfswinkel what is the issue on staging?
@Patrick-Nijman can you add the related github ticket?
