### ISSUE TITLE
Tell users to load their model through 3Di Toolbox

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#206]
It now feels like not much has happened after a new schematisation has been succesfully created or downloaded I suggest a pop-up with the following text:

"Schematisation {schematisation name} ({schematisation nr}) created / downloaded !

Please use the 3Di Toolbox to load it to your project from the Spatialite ({path to spatialite})."

**Comment by leendertvanwolfswinkel** [comment]
The path in the popup has a mixture of forward and backslashes ('C:/Users/leendert.vanwolfswin/Documents/3Di\My third schematisation (38)\revision 1\schematisation\My third schematisation.sqlite').

I tried copy-pasting the path to the 3Di Toolbox, but this doesn't work because of the forward slashes. Please make sure the path conforms to the operating system conventions.

**Comment by ldebek** [comment]
@leendertvanwolfswinkel I've pushed the fix for this issue. Could you please check if the filepath is valid now?

**Comment by leendertvanwolfswinkel** [comment]
Yes perfecto
