### ISSUE TITLE
[Bug]: 3Di login gives python error 

### ISSUE THREAD

**Issue by maudvandelden** [nens/threedi-api-qgis-client#215]
### Contact Details

maud.vandelden@nelen-schuurmans.nl

### Complexity

easy

### Priority

medium prio

### What happened?

![image](https://user-images.githubusercontent.com/59925369/145187854-624236ca-5b1a-4959-a4e9-7fcd4da511ae.png)
logging in gives: Python fout: Er is een fout opgetreden bij het uitvoeren van Python code: Bekijk berichtenlog (Python Error) voor meer details.

![image](https://user-images.githubusercontent.com/59925369/145187964-25e82a3d-fee7-420b-950c-4ace48ca55ff.png)

### How to Reproduce?

Login to the 3Di MI in version threedi_api_qgis_client.2.99.1

### What did you expect and what was the actual result?

expected no error (though i'm logged in)

### Add screenshots, video's etc

The maximum size for files is 25MB and the maximum size for images is 10MB.
![image](https://user-images.githubusercontent.com/59925369/145188155-4bf95a21-cc1c-4290-8e61-ca04abb2fdde.png)

![image](https://user-images.githubusercontent.com/59925369/145188206-87e4e5f8-e65c-415a-a1e2-8c013753e474.png)

### Additional info

Anything else you would like to share?

**Comment by maudvandelden** [comment]
@leendertvanwolfswinkel I wanted to assign you

**Comment by ldebek** [comment]
Fix is available on the `klondike_development` branch.
