### ISSUE TITLE
Improve handling large lateral file uploads

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#216]
In the current implementation, if the processing of a lateral file takes longer than the lateral timeout, the user gets an unclear error (`3Di MI : Error: Uploaded file has not been processed (https://api.3di.live/v3/simulations/51469/events/lateral/file/2475/)`)

Suggested fix:
- [x] Increase the default value for lateral upload timeout from 45 s to 900 s (15 minutes). (already in the current implementation the simulation will start as soon as the laterals have been processed, so the 15 minutes will never be fully used)
- [x] - Move the waiting for the simulation to start to a background thread, so that the user is not bothered by it

**Comment by ldebek** [comment]
Changes available on master.

**Comment by leendertvanwolfswinkel** [comment]
Added this line https://github.com/nens/threedi-api-qgis-client/blob/324349de2c9bffd01066442209438281ce96eb1e/threedi_models_and_simulations/settings.py#L120 because the default value was still 45 and would only update to 900 after clicking 'use defaults'. @ldebek please check if this is right (should have made a PR but already pushed to master)

**Comment by ldebek** [comment]
I've added few additional changes. @leendertvanwolfswinkel feel free to test it again.
