### ISSUE TITLE
[Bug]: Screen closes when entering search command in "Choose model and simulation

### ISSUE THREAD

**Issue by PySjon** [nens/threedi-api-qgis-client#218]
### Contact Details

sjon.vandijk@nelen-schuurmans.nl

### Complexity

easy

### Priority

low prio

### What happened?

When you search for a simulation (by pressing "New Simulation") you have to press enter after writing down a search tag (e.g. "Parramatta") .  But when you press enter, you also close the screen. So you have to open it up again to see your search results. 

### How to Reproduce?

1. Press Simulate
2. Press New Simulation
3. Type your search inquery in the search bar
4. Press enter

### What did you expect and what was the actual result?

I expected to see my search results, but the screen closed. 

### Add screenshots, video's etc

The maximum size for files is 25MB and the maximum size for images is 10MB.

### Additional info

Anything else you would like to share?

**Comment by leendertvanwolfswinkel** [comment]
Fixed
