### ISSUE TITLE
Downloaded sqlite is corrupt

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#219]
* threedi-api-qgis-client version: 2.99.1

For some downloaded schematisations, the sqlite that is downloaded is corrupt. E.g. if you load it using the 3Di toolbox or try to connect to it using the QGIS database manager, you get the error 'File is not a database'

Example: schematisation nr. 74 "demo_org_noordpolder - noordpolder - 1 default", revision 1.

If the same sqlite is downloaded through swagger, it is OK. So it seems that it is not a backend issue; please verify this. If it is a backend issue, we need to know asap.

**Comment by leendertvanwolfswinkel** [comment]
How I downloaded the sqlite through swagger:

find revision id: https://api.staging.3di.live/v3-beta/schematisations/74/revisions/?number=1
get download link: https://api.staging.3di.live/v3-beta/schematisations/74/revisions/3412/sqlite/download/
download sqlite from https://files.staging.3di.live/3di/51533/noordpolder.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=3di%2F20211213%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20211213T135948Z&X-Amz-Expires=172800&X-Amz-SignedHeaders=host&X-Amz-Signature=ef8028ff4f03886813787639974f55ef7f5c97ffea0b1761a4e4f81da332c796

**Comment by ldebek** [comment]
Please re-upload data for schematisation revisions that have plain sqlite file uploaded already.

**Comment by leendertvanwolfswinkel** [comment]
Works fine, except that the path to the spatialite in the popup message is no longer correct because the basename of the .zip is different then the basename of the unzipped .sqlite

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Issue with wrong sqlite file basename should be fixed now.

**Comment by leendertvanwolfswinkel** [comment]
Tested
