### ISSUE TITLE
Enable New Upload button also if no schematisation has been loaded

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#225]
If no schematisation has been loaded yet, it still should be able to click the 'new upload' button -> user should be notified that they need to load a schematisation first and the 'load local schematisation' dialog should appear

**Comment by ldebek** [comment]
Opening  'load local schematisation' dialog will be added along with changes requested in ticket #335

**Comment by leendertvanwolfswinkel** [comment]
I think you forgot that last bit so I added it in https://github.com/nens/threedi-api-qgis-client/pull/338
