### ISSUE TITLE
Do not log 'commit revision' as failed when making threedimodel fails

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#226]
If schematisation data is uploaded correctly, but making a threedimodel fails due to schematisation errors, the logging states COMMMIT REVISION --> failed. But it seems that the revision *has* been committed succesfully (as it should).

**Comment by leendertvanwolfswinkel** [comment]
I put an example in schematisation 'leendert' revision 32

**Comment by ldebek** [comment]
@leendertvanwolfswinkel It seems that I don't have access to it anymore.

**Comment by leendertvanwolfswinkel** [comment]
Tested
