### ISSUE TITLE
When new upload starts, check if loaded model (3Di Toolbox) is same as loaded schematisation (3Di API Client)

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#235]
If this isn't the case, warn the user about this

Perhaps we can include this in the overview page of the upload wizard?

**Comment by Jonasvsl** [comment]
@leendertvanwolfswinkel @Patrick-Nijman this seems high priority to me. why not include in this weeks sprint?
