### ISSUE TITLE
Main Panel simple UI fixes

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#240]
- [x] User name should be e.g. 'Leendert van Wolfswinkel', not 'leendert.vanwolfswin'
- [x] Remove 'Directory' value box
- [x] Show tooltip on hovering over the schematisation name, showing the path for the current schematisation (not the general 3Di working dir!)
- [x] Make schematisation name clickable -> clicking it opens the directory of the current schematisation in Windows Explorer (or other OS equivalents)
- [x] Remove log in button (#256)

**Comment by leendertvanwolfswinkel** [comment]
When the schematisation name is long, the dock widget becomes very wide. Perhaps if the name doesn't fit, cut it off with ... at the end?

![image](https://user-images.githubusercontent.com/26224299/151430188-fd71ea34-e559-454e-8f48-ebdef7346ae8.png)

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Cutting schematisation name does not looks nice imho. I think that moving this label into scrollable area is a bit better option (all information will stay preserved).
![image](https://user-images.githubusercontent.com/11883222/151775297-9ff57253-cb63-4a18-bf40-7eb6f13e138f.png)

**Comment by leendertvanwolfswinkel** [comment]
I don't like the scroll bar either... three options:
1. Cut off the name; to see the whole name, the user has two make the panel wider
2. Inlude the full name in the tooltip (i.e. the tooltip will have two lines, one with the schem. name, other with path)
3. If you select the text and move to the right, the text moves with it (as in a linedit widget)

I prefer a combination of 1&2
