### ISSUE TITLE
Enhance local revision management

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#243]
Changes are required in the local directory structure, upload and download logic, and load local schematisation logic. Outlined in this drawio document (contains 4 tabs):

https://nelenschuurmans.sharepoint.com/:u:/r/sites/Lutra/Gedeelde%20documenten/General/Local%20revision%20management.drawio?csf=1&web=1&e=FaG0vN

**Comment by Patrick-Nijman** [comment]
See attached DrawIO jpg export

**Comment by leendertvanwolfswinkel** [comment]
done. any further improvements will be put in separate tickets
