### ISSUE TITLE
Improvements in dialog New Simulation  > Choose model

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#245]
- [x] Column 'repository' should be replaced by 'schematisation'. 
- [x] Columns 'revision', 'last update' and 'updated by' are not visible unless user scrolls to the side. I think most users will never discover that these columns exist. Solutions may include giving the columns 'model' and 'schematisation' a smaller default width; and/or increase the default width of the whole dialog.
- [x] Replace 'Organisation:' by 'Billing goes to:'
- [x] Filter threedimodels so that only post-Klondike threedimodels are listed (new filter option revision__schematisation__isnull==False)
- [x] sort results newest-at-top
- [x] prefill the search bar with the name of the currently loaded schematisation (if any) and show the results for that schematisation (#273)
- [x] Remove 'Fetch Simulation Templates' button
- auto-fetch when user clicks on a model in the list
- select the most recent simulation template, so that the user can click next
- [x] add a column with the model id

**Comment by Jonasvsl** [comment]
Also: Please add a column with the model id in this overview:
![image](https://user-images.githubusercontent.com/1453159/151131047-a3ac67e3-7ec7-49c7-81c5-18f66fe54a32.png)

**Comment by ldebek** [comment]
Sorting is not implemented on a backend yet, so temporary there will be a sorting per page only.
