### ISSUE TITLE
[3Di]: Boundary conditions need to be used and uploaded when starting a new simulation

### ISSUE THREAD

**Issue by Patrick-Nijman** [nens/threedi-api-qgis-client#250]
### Contact Details

Patrick

### What happened?

Boundary Conditions should be uploaded to the server when a simulation is created. 

![38b3fe02-3721-4bc7-b8bd-d317851e3840](https://user-images.githubusercontent.com/86961942/148371981-47f12842-b0f8-450e-aa5c-ff0f50fa67e3.jpg)

For the short term we need the following fix:
- in the simulation template on the server that is loaded in in the wizard there are time series for the boundary conditions. this file needs to be copied in the plugin and submitted as well when the user starts a simulation

Jelle or Casper can help with this if needed. don't hesitate to ask them, they are available for this

for the long term:
- we need an extra screen for boundary conditions, but for this we need to make designs

**Comment by Jonasvsl** [comment]
Fixed
