### ISSUE TITLE
Read dry weather flow from simulation template

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#254]
In the next API release (expected available 17 jan), dry weather flow will be included as a separate category in the simulation templates. This should be read from the template to prepopulate the simulation wizard

**Comment by ldebek** [comment]
Please update your system threedi-api-client to the one from wheel: https://github.com/nens/threedi-api-qgis-client/blob/klondike_development/threedi_api_qgis_client/deps/threedi_api_client-4.0.0b3.dev0-py2.py3-none-any.whl

**Comment by Jonasvsl** [comment]
A few observations:
- going back and forth in the wizard 'empties' the template from the wizard, causing a crash
- running longer than 24 h is either not picked  up by the backend or the front end is missing a parameter
- I thought that as a user you can give a value for every hour, so for 24 hours we have a table indication what percentage of the dry weather flow is going to be released in that hour. I think it is vital to have this in the wizard as for normal rain events user most likely want a constant dwf. we can also make a checkmark indication you want a constant dwf and then calculate for the user that that means 0.0416 every hour. I believe this should be in the daily attribute of the endpoint
-

**Comment by ldebek** [comment]
First issue `going back and forth in the wizard 'empties' the template from the wizard, causing a crash` should be fixed now. Rest is either backend issue or enhancement request.
