### ISSUE TITLE
Handling tags in simulation templates

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#258]
- Automatic tags should not be read from the simulation template (e.g. 'API-v3', 'core-2.1.1', etc.) 
- User-added tags should be read from the template
- In v2.99.5, the tags are not read correctly, I get "[, ', A, P, I, -, v, 3, ', ,,  , ', c, o, r, e, -, 2, ., 2, ., 2, ', ,,  , ', f, r, a, m, e, w, o, r, k, -, 2, ., 1, 0, ., 0, ', ]"

I don't know if and how automatic tags can be distinguished from user tags.

**Comment by Jonasvsl** [comment]
agree

**Comment by leendertvanwolfswinkel** [comment]
Example model / sim. template:
![image](https://user-images.githubusercontent.com/26224299/149966481-7e37f3dc-a79d-4dcf-882a-c2923392fff8.png)

Results in:
![image](https://user-images.githubusercontent.com/26224299/149966595-c67fdecd-f028-415f-9431-2e9f0cf4ff42.png)

using the version of 18 jan (commit 5ed82c1c28ddc1715fea06632185ae55e9740861 )

**Comment by Jonasvsl** [comment]
version 2.99.6 no issue for me
![image](https://user-images.githubusercontent.com/1453159/150315065-1896f1e6-5b8e-428b-b2dc-7977d5fb3b67.png)

the biggest issue is that these automated tags are in the template. with every run they are added anyway. so they should be skipped when reading in

not sure how the comma seperated issue occurs that you have
maybe some setting in qgis?

**Comment by leendertvanwolfswinkel** [comment]
If I understand correctly, the version tags will be replaced by a dedicated property in the simulation (version_info or something), which can than be ignored when reading in the simulation template. @jpprins1 please confirm so I can close this ticket
