### ISSUE TITLE
Do not prepopulate the 'name' field in the simulation wizard

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#260]
To avoid that users create multiple simulations with the same name, which is just confusing for them

**Comment by leendertvanwolfswinkel** [comment]
@Jonasvsl perhaps we should add a read-only text field in the simulation wizard that shows the name that was read from the template? To make it easier for users to use the same naming system for all their simulations?

**Comment by Jonasvsl** [comment]
we can do that. but wouldn't it make more sense to use the name of the simulation template as default name? maybe add a datetime stamp after it to make them all unique? 
for me I always name my simulation template the same as the name of the simulation

**Comment by leendertvanwolfswinkel** [comment]
makes sense. I would put the revision nr. in the name instead of the date/time, but to make it unique date/time is better

**Comment by Jonasvsl** [comment]
I can live with both options
