### ISSUE TITLE
Simplify New Simulations > Options dialog

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#261]
- [x] All options that are irrelevant for the chosen model should be disabled / removed. E.g. 'include breaches' is not relevant if the model does not contain breaches.

- [x] Put the options in three groups: initial conditions; forcings and events; and other options. The images below show how it should be done, **but one thing should be changed** (didn't have time to update the images). "Forcings and events" should be split into two different groups ("Forcings" and "Events"); "Include breaches" and "Include structure control" should be moved to the "Events" group; "Raster edits" will also be added to the Events group once this has been implemented.

![image](https://user-images.githubusercontent.com/26224299/207148204-2e1b9c4d-ee5b-4935-8649-2b3482717efa.png)

Or, when Multiple simulations and Postprocessing in Lizard are checked:
![image](https://user-images.githubusercontent.com/26224299/207147062-c6282dc6-1051-4639-ab6b-2f7df16f6f87.png)

**Comment by leendertvanwolfswinkel** [comment]
The following options should always be available, regardless of the model:
- Include initial conditions
- Include precipitation
- Include laterals
- Include wind
- Generate saved state
- Multiple simulations (same logic as already implemented)
- Post-processing in Lizard

The following options should only be available under specific conditions:
- Load from saved state: only if a saved state is available for this model
- Include boundary conditions: only if boundary conditions are included in the simulation template
- Include structure control: only if the model has 1D (threedimodel property extent_1d != null)
- Include dry weather flow: only if the model has 1D
- Include breaches: only if the model has breach_count > 0

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Changes available for testing on branch 'new_init_option_screen'

**Comment by leendertvanwolfswinkel** [comment]
@ldebek Really happy with this! The only thing I could find that doesn't work the way it should is the Damage Estimation options:

![image](https://user-images.githubusercontent.com/26224299/212755012-ad8758da-a2aa-47ed-916d-c95a2ae5d075.png)

Perhaps it would be easier to give the whole "Post-processing in Lizard" its own page in the wizard (between 'settings' and 'start the simulation')? Than on the options page, we can just have a checkbox 'Post-processing in Lizard'.

**Comment by ldebek** [comment]
@leendertvanwolfswinkel It's actually good idea. I can work on it within extra forcing ticket scope. But for now I just tweaked some UI settings to avoid squeezed widgets. :)

**Comment by leendertvanwolfswinkel** [comment]
Great
