### ISSUE TITLE
Simulation wizard: improve progress bar at top

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#262]
The progress figure with the green dots is helpful, but to add: 

1) include only the steps that are included in the current simulation. 
2) The tab you are working in should not become green yet, since it is not finished. Suggesting to have this only bold 

The figure doesn't downscale proportionally; the figure is compressed

**Comment by ldebek** [comment]
Changes available for testing on branch: `simulation_wizard_step_progress`.
PR: https://github.com/nens/threedi-api-qgis-client/pull/424

**Comment by leendertvanwolfswinkel** [comment]
Two comments:
- The page title is missing ("Initial conditions" in the example above)
- The status panel on the left changes size depending on the contents of the page at the right. E.g. if I include precipitation and set it to None while the dialog is wide, it will make the status panel wider. Please make the status panel fixed width.

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Is extra title on page really needed? For me it just takes extra space and is duplicated information from wizard steps section.

**Comment by leendertvanwolfswinkel** [comment]
Yes please at the title, I think it gives a bit more clarity

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Should it be only on Initial Conditions tab, or on others as well?

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Changes applied.

**Comment by leendertvanwolfswinkel** [comment]
Almost there I think... 

Some comments:
- The progress panel at the left should always be wide enough to fit the largest label in the list (see image below). This may have something to do with the display settings (I duplicate my screen to a second screen, using the Windows default/recommended 125% zoom option)
![image](https://user-images.githubusercontent.com/26224299/210321710-18f555ed-fd6a-4847-8139-fc3dd7d43090.png)
- The right part of the screen can be too small for its contents:
![image](https://user-images.githubusercontent.com/26224299/210333695-0b706a11-1ab6-4238-8a5a-f31c804631de.png)
![image](https://user-images.githubusercontent.com/26224299/210333784-49677af5-4afb-47f6-9491-c12e568bf5d3.png)

**Comment by leendertvanwolfswinkel** [comment]
Nice work!
