### ISSUE TITLE
Simulation wizard: Duration page improvements

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#263]
- [x] #487
![image](https://user-images.githubusercontent.com/26224299/149313913-e6f0a7a0-6bba-44b4-bde4-51d1940b9bb4.png)

- [ ] if you use the tab key to move from widget to widget, the order is not what you'd expect. should be start date > start time > end date > end time
- [ ] Add a time zone widget so that users can select the time zone. the simulation start time should then be converted back to UTC
- [ ] If user selects another time zone than UTC, show the text "Simulation start date and time will be converted to Coordinated Universal Time (UTC): {simulation start datetime}"

**Comment by Overmeen** [comment]
Tested, looks good:

![image](https://github.com/nens/threedi-api-qgis-client/assets/84539501/729b4214-75ba-4f7d-88b0-ea3f67641a5a)

**Comment by leendertvanwolfswinkel** [comment]
@ldebek I would like to make some additional changes before we release this. Specifying the time zone is not relevant for the large majority of use cases. I want to prevent this new feature to cause confusion for users that do not need it.

I think we can achieve this by putting the time zone options in a optional group box: 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0pSIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--faac863e9e0478490c01a92b62495d71a09eaadf/image.png)

This also means that if the "Specify time zone" box is not checked, the start date and time should be interpreted as UTC without applying any conversion.

**Comment by leendertvanwolfswinkel** [comment]
Excellent, please merge @ldebek
