### ISSUE TITLE
Download results to the appropriate folder in the local directory structure

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#287]
- Do not ask where to save results, but follow local directory structure
- Unzip log files after downloading

**Comment by leendertvanwolfswinkel** [comment]
I think I wasn't precise enough in this ticket's description. The behaviour I would like to see is:

- Never save to 'work in progress' directory, but always to 'revision _n_'\results
- Make sure the results are saved to the directory of the schematisation to which the results belong. E.g. if my active schematisation is 'Schematisation A' but I download results that belong to a model generated from revision 23 of Schematisation B, the results should be stored in <3Di work dir>\Schematisation B\revision 23\results\<simulation name>
- If this is not too complex: it would be great if clicking on the green 'download finished' widget would open the directory in windows explorer

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Changes are on repo now (beside last point, as this would take a bit more time to implement).

**Comment by leendertvanwolfswinkel** [comment]
how much time would it take to implement the last point? alternatively, pushing a message like 'Results of simulation {simulation name} downloaded to {path}' would be an option. I am pretty certain that users will now be wondering where their results where downloaded to.

**Comment by ldebek** [comment]
@leendertvanwolfswinkel I've already added results location path in the successful download message. Last point will need some experimenting with QStyledItemDelegate class to achieve what you want. But as an alternative we could add an extra button to open directory of downloaded result files which imho will be nicer and easier approach.
