### ISSUE TITLE
Migrate sqlite to newest schema version before running schematisation checker

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#291]
Migrating sqlites to a newer version is part of the threedi-modelchecker package. This action should be performed before running the checks. If not, it will not be possible to check any schematizations

**Comment by Patrick-Nijman** [comment]
Please use the latest version of the modelchecker within the 3Di Toolbox. Zip is too big to put in here

**Comment by leendertvanwolfswinkel** [comment]
It doesn't work for me unfortunately
Schematisation: "leendert"
Revision:
threedi-modelchecker: 0.25.2
ThreediToolbox: ThreeDiToolbox-casper-checker.zip 

Error:
![image](https://user-images.githubusercontent.com/26224299/151254247-7da16ee7-2a13-49c7-9652-788f5fe2c18b.png)
