### ISSUE TITLE
New schematisation -> update reference -> delete spatialite fails

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#292]
MAKE IT WORK FFS @ldebek 
[Prinseneiland_gw3.zip](https://github.com/nens/threedi-api-qgis-client/files/7906197/Prinseneiland_gw3.zip)

**Comment by ldebek** [comment]
IT'S READY FOR TESTING FFS! @leendertvanwolfswinkel
