### ISSUE TITLE
Login window

### ISSUE THREAD

**Issue by PeterPetrik** [nens/threedi-api-qgis-client#3]
- [ ] Create choose type window 
- [ ] Create login window
- [ ] Test for login API
- [ ] store session 

![Screenshot 2020-02-25 at 09 17 00](https://user-images.githubusercontent.com/804608/75228056-aa85a500-57af-11ea-8025-252d015d3dcd.png)

![Screenshot 2020-02-25 at 09 16 50](https://user-images.githubusercontent.com/804608/75228059-ac4f6880-57af-11ea-887b-4a2b968e6dd9.png)

estimate 1 day

**Comment by DamnBack** [comment]
Implemented
