### ISSUE TITLE
[Bug]: front end in qgis doesn't update to 100% while model is ready to run

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#303]
### What happened?

![image](https://user-images.githubusercontent.com/1453159/150792720-0c20d76a-5969-428f-be1a-dda342a0d32c.png)

https://api.staging.3di.live/v3/threedimodels/15268/tasks/
Model is finished, but front end says it isn't. 
There has been a change in the backend that the inpy succes = true is set before the simulation templates are generated, might that cause this issue?

**Comment by ldebek** [comment]
It seems like `ThreediModel `instance does not have `is_valid ` attribute (Python client). I prepared fix for plugin, but `threedi_api_client` package have to be fixed as well to make it work.
