### ISSUE TITLE
Download results

### ISSUE THREAD

**Issue by PeterPetrik** [nens/threedi-api-qgis-client#31]
1. Click on results
2. Click on test-simulation (1375)
3. Click on download (this should open the users OS folder selection screen)
4. The progress dialog will be displayed the similar fashion  as the
progress in the “Running simulation window”. This will allow users to download
multiple files at the same time and will get a consistent feeling of download and
running actions

<img width="398" alt="Screenshot 2020-04-06 at 11 57 04" src="https://user-images.githubusercontent.com/804608/78546472-c2fccc80-77fd-11ea-8162-87de199f4ae1.png">

**Comment by Jonasvsl** [comment]
A few additions:

**download folder**
I think it would be best if the user selects a folder and then automatically the results are all put in a subfolder called sim_[sim_id]_[simulation_name]

**regarding the multiple files:**

A user typically downloads all files at the same time. So:
- logging
- result_3Di.nc
- aggregation netcdf
- gridadminfile

I have here some python code that does this:

sim_id = 1538
output_path_results = r'c:\temp\api_testing\sim_%s' %sim_id

sim_results = sim_api.simulations_results_files_list(sim_id)
if not os.path.exists(output_path_results):
    os.makedirs(output_path_results)

#create a dict with the results
results = [x for x in sim_results.results ]

#simply download all files that belong to the result:
for result_file in results:
    print ("Downloading: " + result_file.filename)
    download = sim_api.simulations_results_files_download(result_file.id, sim_id)
    with open(output_path_results + os.sep + result_file.filename, 'wb') as f:
        file_data = requests.get(download.get_url)
        f.write(file_data.content)
        print("Downloaded: " + result_file.filename)

and seperately:
#Download gridadmin that comes with it:
threedimodel_id = 12 # On production Bergermeer = 12, on staging = 29
#help (ThreedimodelsApi)
download = threedi_api.threedimodels_gridadmin_download(threedimodel_id)
#api.threedimodels_gridadmin_download(id, async_req=True)
with open(output_path_results + os.sep + 'gridadmin.h5', 'wb') as f:
        file_data = requests.get(download.get_url)
        f.write(file_data.content)
        print("Downloaded: " + 'gridadmin.h5')

**Comment by PeterPetrik** [comment]
> **download folder**
> I think it would be best if the user selects a folder and then automatically the results are all put in a subfolder called sim_[sim_id]_[simulation_name]

@Jonasvsl I am wondering if this setting should not be in the plugin global settings dialog and user will be asked only on the first download to choose location? Or the save location is per-repository/model?

**Comment by Jonasvsl** [comment]
every model is stored in a different folder for the user. usually results are stored with that model that was run, otherwise you go crazy looking for results with models.
so a typical model folder looks like this:

![image](https://user-images.githubusercontent.com/1453159/78637756-4c1e0d00-78ab-11ea-8e59-be86d3f87eb6.png)

Users then store their results in the results folder. Since there can be more than 1 result per model I think it would be best to create subfolders for the user.

 So to answer your question: the save location is per repo/model.

**Comment by Jonasvsl** [comment]
Additional remark: 

Results can be up tot 5 GB large, not sure if QGIS works with time-outs in case a download takes a long time

**Comment by PeterPetrik** [comment]
implemented in 0.5.5
