### ISSUE TITLE
add a tab for control structures

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#313]
The user should have the option to select the default (from spatialite) or to upload a json file to the control structure file upload endpoint (`/v3/simulations/{simulation_pk}/events/structure-control/file/`).

- [ ] Add option "Structure control" in the options dialog
- [ ] When prepopulating this dialog from the simulation template, check this box if any of the relevant properties in the simulation template have non-null values (sections "tablestructurecontrols", "memorystructurecontrols", "timedstructurecontrols", "filestructurecontrols")
- [ ] Add page "Structure control" in the simulation wizard
- [ ] On that page, there should be two options (user should be allowed to check both options): 
    - "From simulation template": any information in the simulation template (sections "tablestructurecontrols", "memorystructurecontrols", "timedstructurecontrols", "filestructurecontrols") is added to the simulation. Please disable this option if there is no such info in the simulation template. Otherwise, this should be the checked option.
    - "Upload file": user selects a *.json file from disk to be uploaded to the `/v3/simulations/{simulation_pk}/events/structure-control/file/` endpoint

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Changes available for testing on https://github.com/nens/threedi-api-qgis-client/tree/structure_controls_handling
Temporarily structure controls page is using `Initial conditions` SVG. This will be sorted after implementing new simulation steps progress bar.

**Comment by leendertvanwolfswinkel** [comment]
- [ ] The checkbox looks like it is disabled (I think this is the case for all checkboxes in the simulation wizard; a bit confusing):
![image](https://user-images.githubusercontent.com/26224299/208504411-7c8b4b6a-4428-43e4-9ba4-e822359917af.png)

- [ ] On the settings page, the groups are now expanded by default, they used to be collapsed by default. Please change this back

Some minor UI changes:
- [ ] Change the text "Upload control structure file:" to "Structure control file:"
- [ ] Change the "Upload" button to "Browse..." or a browse icon

**Comment by leendertvanwolfswinkel** [comment]
Tested. We found some backend issues with structure control files, but the UI stuff works as it should
