### ISSUE TITLE
Simulation template - use forcings that are in template but not in wizard

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#316]
The way the wizard is set up it loads in all the information from the simulation template. However, how does it handle any event that is not in the wizard itself? Are they omitted? It is good to realise that any of the events below can be part of the simulation template. That means we need either a tab for every possibility, or a way of handling events that are not in the wizard template. Here is the complete list:

```
{
    "lizardrasterrain": [],
    "lizardtimeseriesrain": [],
    "timeseriesrain": [],
    "breach": [],
    "lizardrastersourcessinks": [],
    "lizardtimeseriessourcessinks": [],
    "filerastersourcessinks": [],
    "filetimeseriessourcessinks": [],
    "timeseriessourcessinks": [],
    "leakage": [],
    "filetimeseriesleakage": [],
    "filerasterleakage": [],
    "initial_twodwaterlevel": {},
    "initial_onedwaterlevelpredefined": null,
    "initial_groundwaterlevel": null,
    "initial_groundwaterraster": null,
    "initial_onedwaterlevel": null,
    "initial_onedwaterlevelfile": {},
    "initial_twodwaterraster": null,
    "filerasterrain": [],
    "filetimeseriesrain": [],
    "initial_savedstate": null,
    "savedstates": [],
    "laterals": [],
    "filelaterals": [],
    "fileboundaryconditions": {},
    "tablestructurecontrols": [],
    "memorystructurecontrols": [],
    "timedstructurecontrols": [],
    "filestructurecontrols": [],
    "rasteredits": [],
    "localrain": [],
    "wind": [],
    "initial_winddragcoefficient": null
}
```

My analysis (please verify this!) is that we have no options for the following events:

```
{
    "lizardtimeseriesrain": [],
    "lizardrastersourcessinks": [],
    "lizardtimeseriessourcessinks": [],
    "filerastersourcessinks": [],
    "filetimeseriessourcessinks": [],
    "timeseriessourcessinks": [],
    "leakage": [],
    "filetimeseriesleakage": [],
    "filerasterleakage": [],
    "filetimeseriesrain": [],
    "tablestructurecontrols": [],
    "memorystructurecontrols": [],
    "timedstructurecontrols": [],
    "filestructurecontrols": [],
    "rasteredits": [],
    "localrain": [],
    "wind": [],
    "initial_winddragcoefficient": null
}
```

**Comment by leendertvanwolfswinkel** [comment]
Show as (disabled) options in the options screen:
- [ ] raster edits
- [ ] structure control
- [ ] leakage
- [ ] sources & sinks

**Comment by leendertvanwolfswinkel** [comment]
- [ ] Include: give the whole "Post-processing in Lizard" its own page in the wizard (between 'settings' and 'start the simulation'). Than on the options page, we can just have a checkbox 'Post-processing in Lizard'.

**Comment by ldebek** [comment]
> * [x]  Include: give the whole "Post-processing in Lizard" its own page in the wizard (between 'settings' and 'start the simulation'). Than on the options page, we can just have a checkbox 'Post-processing in Lizard'.

There is separate PR just for this part of the ticket: https://github.com/nens/threedi-api-qgis-client/pull/432

**Comment by leendertvanwolfswinkel** [comment]
One option I forgot (did not exist yet when this ticket was made): 
- [ ] Obstacle edits ("obstacleedits")

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Handling (partial) of the extra forcing options available for testing on `forcings_from_template` branch. Handling of the few events ("leakage", "filetimeseriesleakage", "filerasterleakage", "filerastersourcessinks", "filetimeseriessourcessinks", "filetimeseriesrain") needs clarification and will be implemented later in the future.

**Comment by leendertvanwolfswinkel** [comment]
@ldebek I tried a template with a raster edit, but I got this error:

```
AttributeError: 'Event' object has no attribute 'raster_edits' 
Traceback (most recent call last):
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di MI testing/python/plugins\threedi_models_and_simulations\widgets\simulation_wizard.py", line 2529, in run_new_simulation
    init_options.raster_edits = events.raster_edits[0]
AttributeError: 'Event' object has no attribute 'raster_edits'
```

**Comment by ldebek** [comment]
@leendertvanwolfswinkel I've pushed fix which should sort out this issue. Feel free to test it again.

**Comment by leendertvanwolfswinkel** [comment]
@ldebek Issue seems to be fixed; next problem I run into is: 

`3Di Models and Simulations : Error: simulations_events_raster_edits_create() missing 1 required positional argument: 'data'`

**Comment by leendertvanwolfswinkel** [comment]
I will make an example simulation template for you to test

**Comment by leendertvanwolfswinkel** [comment]
I created a simulation template for the model "Demo model 1d2d (Lutra)", revision 11, called "Raster and obstacle edit"

**Comment by ldebek** [comment]
@leendertvanwolfswinkel I've pushed a fix for issue above, but now I'm getting `500` code from server while trying to create new raster edits.

**Comment by leendertvanwolfswinkel** [comment]
I've asked the backend team if they can find the problem with this

**Comment by leendertvanwolfswinkel** [comment]
What value do you pass to the endpoint in the 'raster' argument? 

@jpprins1 suspects there is a backend bug in that the server would not except 
`"raster": "https://api.3di.live/v3/threedimodels/54254/rasters/127740/"`
while it would except 
`"raster": "https://api.3di.live/v3/threedimodels/54254/raster/127740/"`

**Comment by ldebek** [comment]
@leendertvanwolfswinkel It's `'raster': 'https://api.3di.live/v3/threedimodels/54254/rasters/127740/'` Value is taken directly from simulation template event `rasteredits`.

**Comment by leendertvanwolfswinkel** [comment]
@ldebek the bug will be fixed soon (probably this week), so I will continue testing after that has been released to staging. No action required from you at the moment

**Comment by leendertvanwolfswinkel** [comment]
@ldbek I have tested the most important parts. Please merge :)

You can ignore the other pull request that Casper and I made yesterday
