### ISSUE TITLE
Automatically update base URL from https://api.3di.live/v3.0 to https://api.3di.live

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#318]
This is stored in the user profile, so updating the plugin will not update the URL. Please auto-update

**Comment by ldebek** [comment]
@leendertvanwolfswinkel "Use defaults" in the plugin settings will give you a new URL.

**Comment by leendertvanwolfswinkel** [comment]
Ok so perhaps we just need a better check & feedback message to users if the base url is wrong. Now, if I enter the wrong base url, I get: 
![image](https://user-images.githubusercontent.com/26224299/152181961-5527481f-f9ca-4eaa-9a89-e3d1ec532db1.png)

**Comment by ldebek** [comment]
Dedicated message added.

**Comment by leendertvanwolfswinkel** [comment]
Please change the message to:

"""Error: Invalid Base API URL 'https://api.3di.live/v3.0'. The 3Di API expects that the version is not included. Please change the Base API URL in the 3Di Models & Simulations plugin settings."""

So that users know to fix the issue. Or even open the settings window for them after they close the error message if that isn't too complicated.

**Comment by ldebek** [comment]
Error message changed.
