### ISSUE TITLE
It is no longer possible to upload a DWF file < 24h

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#320]
"Invalid": "Daily periodic lateral files should only have 25 timestamps: 0 - 24 * 3600, this one has [0.0, 3600.0, 7200.0, 10800.0, 14400.0]" 

Perhaps instead of changing this, we should change te DWF calculator to always output 24h timeseries? @Jonasvsl what do you think?

**Comment by Jonasvsl** [comment]
maybe we should remove it at some point as dwf is calculated on the server. What would be the reason to still have a local tool?
