### ISSUE TITLE
New schematisation: add option to use existing spatialite

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#326]

**Comment by leendertvanwolfswinkel** [comment]
Currently, users are forced to go through the whole wizard when they create a new schematisation. The wizard helps them to choose the settings for their new spatialite. 

However, users often already have an existing spatialite that they want to use. These users should not need to go through the wizard. Therefore, please make going through page 2 and 3 of the wizard optional. Adapt the first page of the wizard like in the figure below. 

- By default, the option 'Create New Spatialite' is checked
- If the user selects a file, the 'Choose File' option should be checked automatically
- If the user clicks next and 'create new spatialite' is checked, show page 2 & 3 of the wizard
- If the user clicks next and 'Choose File' is checked, do not page 2 & 3 of the wizard. Copy the selected spatialite to the work in progress\schematisation folder of the new schematisation instead.

![image](https://user-images.githubusercontent.com/26224299/161553158-cf0a102b-d2cc-49cc-bbe3-21a98d543815.png)

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Fix for the issue with misleading error message is on master branch now. For the attribute changes in the `v2_global_settings` table I'm assuming that it's result of missing rasters under specified location. According to what @erpas said - in that case those fields might get empty.

**Comment by leendertvanwolfswinkel** [comment]
tested
