### ISSUE TITLE
Main panel UI improvements

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#335]
After implementing this ticket, the main panel should look like this (with some exceptions, see below):

https://www.figma.com/file/MwePfiTsdPlJCePXUEpZnC/Modeler-Interface?node-id=39%3A37
![image](https://user-images.githubusercontent.com/26224299/153476423-5b5af6cf-bc9c-41e6-a65c-1b803f52cbc5.png)

To do's:

- In the design it says 'Not logged in (click to log in)' - this does _not_ have to be implemented
- [x] Once logged in, at the right of the user name, a small button with (x) icon must appear. Clicking the button should log the user out. The button tooltip must be 'Log out'
- [x] If no schematisation is active yet, the instead of the schematisation name, it should say "Choose...". Clicking this text should open the 'Load local schematisation' dialog
- [x] Same for revision
- [x] Next to the schematisation there should be small buttons with a '->' icon. Clicking it should open the 'Load local schematisation' dialog. The tooltip must be 'Activate a locally available revision of a schematisation'
- [x] Same for revision
- [x] Remove BUILD button
- [x] Add a group box 'Schematisation' to the main panel, with the buttons 'Download', 'Upload', 'New' (in that order). In the design, the buttons have text below them, but I think adding a tooltip instead is a better idea. Tooltip texts: Download -> "Download a revision of a schematisation"; Upload: "Upload changes, creating a new revision of the current schematisation"; New -> "Create new schematisation. It will be created both on the server and locally"
- [x] Add MANAGE button. Clicking the button should open https://management.3di.live/ in the browser
- [x] Make the system feedback collapsed
- [x] Remove the 'Clear log' button

**Comment by ldebek** [comment]
All changes beside clickable "Choose..." text for revision are implemented. That clickable label is a bit more work, so I can either add it on Monday or just skip that part as same logic is triggered by clicking arrows for schematisation/revision.
