### ISSUE TITLE
Parse API Error strings

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#351]
Errors from the API like ```Error: {"detail":"This action requires the role 'Creator' in the organisation that owns this object."}``` should be parsed to ```Error: This action requires the role 'Creator' in the organisation that owns this object.```

**Comment by leendertvanwolfswinkel** [comment]
I still get the non-parsed error 
![image](https://user-images.githubusercontent.com/26224299/170239807-f6a64907-8376-4d29-876c-2649304bbf37.png)

**Comment by ldebek** [comment]
@leendertvanwolfswinkel During which action this error occurs?

**Comment by leendertvanwolfswinkel** [comment]
How you can reproduce this: create a new schematisation on Nelen & Schuurmans Technology (on production). Your 'Creator' rights for this org have just been revoked, so you should get the error I also got.

Of course, this is just an example; this parsing of messages should work for all errors coming from the API
