### ISSUE TITLE
OAuth2 authentication

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#352]
The authentication method for the 3Di API will change in the first half of 2022. Username/passwords of existing users will still work, but only until they change their password.

On staging, the 3Di API is able to accept OAuth2 Bearer tokens. QGIS must obtain such a token by opening up a browser window and catch the obtained token through a redirect. The technical term is "Authorization code grant with PKCE extension", where QGis takes the role of "client" and the 3Di API the role of "resource server". We need to find out if this is possible in QGIS. An example (in Python) is here: https://github.com/nens/threedi-api-client/pull/76

QGIS can use the following data. This data may also be shared publicly.
issuer = "https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_vPwXOnNbi"
client_id = "73d21iv9pu333mjqpbguipa7pi"
scope = "staging.3di.live/*:readwrite"
redirect_uri = "https://api.staging.3di.live/static/drf-yasg/swagger-ui-dist/oauth2-redirect.html"
The resulting access + refresh tokens should be stored securely in the QGIS password manager.

The access tokens must be attached to requests as a Bearer token. threedi-api-client has support for this. The current master version of threedi-api-client is also able to refresh oauth2 tokens. Keep in mind that refresh tokens can also expire, so API requests can go wrong and you have to go through the login again.

If the implementation goes well, @caspervdw will create new client ids especially for QGis (2x, production and staging). 

Please let @caspervdw know which redirect_uri he should set to land in QGis again

**Comment by ldebek** [comment]
Functionality available for testing on branch `oauth2_authorization`.

**Comment by caspervdw** [comment]
Apparently the QGis implementation of the normal Authorization Code Flow isn't working out as expected? 

I don't think the current approach is a good one; we assume here that the Cognito login screen implementation is a stable API. A change to the login screen may be done by the Cognito developers at any time, without warning beforehand. Then our QGis plugin will break. It may never happen, but there are no guarantees.

So if the OAuth2 flow indeed doesn't work out, we have to use Personal API Keys. A user should generate one on the management screens (not yet implemented) and configure it one-time in QGis. A bit like the Google API plugin (I was told).
The personal API key can then be included as password (and username=`__key__`)

**Comment by ldebek** [comment]
@caspervdw The issue with QOAuth2AuthorizationCodeFlow is that PyQT bindings were part of the QGIS instalation in the previous QGIS LTR (3.16) which was compiled with QT 5.11. New LTR (3.22) is compiled against QT 5.15, while since QT 5.12 release QOAuth2AuthorizationCodeFlow (as part of the PyQT QtNetworkAuth module) was moved to separate package which is not included within PyQT shipped with the latest LTR. And installation of it is not straightforward as it's not pure Python library. Alternative approach is to use QTcpServer that will listen localhost on the predifined port and catch redirect_url with an authorization_code. Not very elegant approach, but it should work.

**Comment by caspervdw** [comment]
> Alternative approach is to use QTcpServer that will listen localhost on the predifined port and catch redirect_url with an authorization_code. Not very elegant approach, but it should work.

I don't think that is a good approach; local systems differ. Maybe the port is already in use, for example.

I think that packaging the `QOAuth2AuthorizationCodeFlow` in the new QGis (LTR 3.22) is the only option, else we should reside to API keys.

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Alternative method of an OAuth2 authorization (QTcpServer approach) is ready for testing on branch `oauth2_authorization_tcp_server`.

**Comment by leendertvanwolfswinkel** [comment]
Windows Defender Firewall blocks logging in; many users won't have admin privileges to allow access:

![image](https://user-images.githubusercontent.com/26224299/164645877-e23c611b-4ba8-49dd-bf16-b6d17427744c.png)

**Comment by leendertvanwolfswinkel** [comment]
The browser window opens; I then choose the 'NelenSchuurmans corporate id' option. I then get this window: 
![image](https://user-images.githubusercontent.com/26224299/164646259-8a05cde1-f6a7-4c27-8b7c-27ec547be399.png)

**Comment by leendertvanwolfswinkel** [comment]
Then, when I try to cancel loggin in, I get this error:

```
TypeError: 'method' object is not connected 
Traceback (most recent call last):
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\OAuth2/python/plugins\threedi_models_and_simulations\widgets\log_in.py", line 326, in reject
    self.authorization_handler.tokens_acquired.disconnect(self.log_in_threedi)
TypeError: 'method' object is not connected
```

And the only way to proceed is to kill qgis through Task Manager

**Comment by leendertvanwolfswinkel** [comment]
On production, the client id should be different from the one on staging. @caspervdw please tell @ldebek which one to use

**Comment by leendertvanwolfswinkel** [comment]
On staging, everything works fine now, except that the browser shows me this message, which makes it appear as if logging in has failed:

![image](https://user-images.githubusercontent.com/26224299/169825448-cce1ea6b-3c3c-4ff0-adec-8a59c04d3ed0.png)

@ldebek if I understand correctly, to change this, something needs to be changed at 'your' side of things?

**Comment by leendertvanwolfswinkel** [comment]
Current implementation is functional. Still missing:

- The resulting access + refresh tokens should be stored securely in the QGIS password manager
- Support for urls like api.3di.tw and possibly other urls in the future
- Handling the case where something goes wrong (i.e. slow connection -> timeout). Currently this leads to a situation where QGIS needs to be killed through the Windows Task Manager
- Replacing the ERR_EMPTY_RESPONSE page with a "Success, please return to QGIS"-like page

Discussion is needed whether to continue on this path or opt for storing API Keys

**Comment by leendertvanwolfswinkel** [comment]
We have decided that the OAuth2 route will not be continued and we will direct users to get and store an API Key. Closing this ticket and creating a new one for that.
