### ISSUE TITLE
New schematisation: migrate spatialite to most recent version

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#359]

**Comment by leendertvanwolfswinkel** [comment]
Tested. Excellent workflow. Please merge with master

**Comment by leendertvanwolfswinkel** [comment]
oops wrong ticket

**Comment by leendertvanwolfswinkel** [comment]
on which branch is this? I tested with pak_authorisation branch, but it is not fixed there

**Comment by ldebek** [comment]
@leendertvanwolfswinkel This one is on "master"

**Comment by leendertvanwolfswinkel** [comment]
@ldebek I am not sure if we both have the same understanding of this ticket. What I mean is that when a user creates a new schematisation, the sqlite that is used for that should be migrated to the newest schema version. And/or, the sqlite that is shipped with the plugin (in `_data` should be migrated to the current highest schema version)

**Comment by ldebek** [comment]
Changes available on branch: https://github.com/nens/threedi-api-qgis-client/tree/migrate_spatialite_on_new_schematisation

**Comment by leendertvanwolfswinkel** [comment]
I tested it and discovered two issues. 

1. After creating the schematisation, I get the following error:
`2022-09-13T21:04:13     CRITICAL    3Di Models and Simulations : Error: table v2_aggregation_settings has no column named aggregation_in_space`. My guess is that you first migrate the spatialite and then try to fill the aggregation settings with a query that still has a `aggregation_in_space` column. This column was removed in a previous migration.
2. The value for `v2_numerical_settings.max_degree` is 90 degrees. In a previous migration, the units of this field were changed from degrees to radians. Please change the default value from 90 to `0.5 * pi()`

**Comment by ldebek** [comment]
Fix available on branch: `compatibility_with_schema_208`

**Comment by leendertvanwolfswinkel** [comment]
Tested

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Changes done.
