### ISSUE TITLE
[3Di]: Laterals input spatialite in minutes - output in seconds?

### ISSUE THREAD

**Issue by Patrick-Nijman** [nens/threedi-api-qgis-client#361]
[ ] https://github.com/nens/servicedesk-issue-only/issues/37

### What priority should we assign to this submission?

Prio3 Not urgent

### What happened?

If we detect laterals inside the SQLite then it states [FROM TEMPLATE], the unit is in seconds. In the spatialite we enter the unit in minutes but the simulation template converts this to seconds. If this is true we need to make a tooltip. I think it's better to use the same unit when we display something to the user. This is a bit confusing. 

![image](https://user-images.githubusercontent.com/33685743/159711576-6b191969-ee64-4f4c-9742-0dee214a02b7.png)

### How to Reproduce?

Check https://docs.3di.live/d_simulate_modeller_interface.html?highlight=laterals#laterals

**Comment by leendertvanwolfswinkel** [comment]
Closing, will double-check when re-design of laterals page is done
