### ISSUE TITLE
Make Rainfall CSV accept non-equidistant timesteps

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#362]
The current CSV file upload for rainfall accepts only equidistant timesteps for rainfall

Like this:

```
0,0
5,0
10,0.136658
15,0.136658
20,0.136658
```

But users for whatever reason sometime do this:

```
0,0.0
815,0.0
820,0.136658
825,0.136658
830,0.136658
835,0.136658
```

Since the timestep is calculated by looking at the first and second entry in the csv, this will give horribly too low results for rainfall. 

The most logical would be to accept non equidistant timesteps when users upload a mm/timestamp CSV for rainfall. If that is not possible the above example should NOT be accepted by the user interface.

**Comment by leendertvanwolfswinkel** [comment]
User now gets a warning if non-equidistant timestep is used
