### ISSUE TITLE
rainfall csv should be able to accept more than 300 lines

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#363]
the current csv can only contain 300 lines. this is an api restriction on the endpoint. 

For users it is not possible to upload CSV's with more lines. 

To solve this issue there are two options:

1. Cut larger CSV's in sections and upload them seperately
2. Upload the CSV as a NetCDF time series. Then the 300 limit is gone. 

@daanvaningen  Can you attach an example of a NetCDF with valid timeseries for 3Di to this ticket?

**Comment by daanvaningen** [comment]
https://github.com/nens/threedi-api-qgis-client/issues/363

**Comment by Jonasvsl** [comment]
taking into consideration that the NetCDF route is broken I propose a solution where the csv is simply cut into smaller pieces for the API to handle. 

it will also make it easier for users to see in the api what actually was used in the simulation

**Comment by leendertvanwolfswinkel** [comment]
Duplicate: #162

I think this issue exists more generally for all time series csv uploads, right? (e.g. 1D/2D laterals & boundary conditions, perhaps also wind?). A more generic fix might be same effort to fix all of them

**Comment by ldebek** [comment]
@Jonasvsl Do you have any example CSV file, which I could use for testing?

**Comment by Jonasvsl** [comment]
0,0
5,0
10,0.136658
15,0.136658
20,0.136658
25,0.136658
30,0.136658
35,0.136658
40,0.136658
45,0.136658
50,0.136658
55,0.136658
60,0.136658
65,0.136658
70,0.136658
75,0.136658
80,0.136658
85,0.136658
90,0.136658
95,0.136658
100,0.136658
105,0.136658
110,0.136658
115,0.136658
120,0.136658
125,0.136658
130,0.136658
135,0.136658
140,0.136658
145,0.136658
150,0.136658
155,0.136658
160,0.136658
165,0.136658
170,0.136658
175,0.136658
180,0.136658
185,0.136658
190,0.136658
195,0.136658
200,0.136658
205,0.136658
210,0.136658
215,0.136658
220,0.136658
225,0.136658
230,0.136658
235,0.136658
240,0.136658
245,0.136658
250,0.136658
255,0.136658
260,0.136658
265,0.136658
270,0.136658
275,0.136658
280,0.136658
285,0.136658
290,0.136658
295,0.136658
300,0.136658
305,0.136658
310,0.136658
315,0.136658
320,0.136658
325,0.136658
330,0.136658
335,0.136658
340,0.136658
345,0.136658
350,0.136658
355,0.136658
360,0.136658
365,0.136658
370,0.136658
375,0.136658
380,0.136658
385,0.136658
390,0.136658
395,0.136658
400,0.136658
405,0.136658
410,0.136658
415,0.136658
420,0.136658
425,0.136658
430,0.136658
435,0.136658
440,0.136658
445,0.136658
450,0.136658
455,0.136658
460,0.136658
465,0.136658
470,0.136658
475,0.1016667
480,0.1039167
485,0.1063333
490,0.109
495,0.1118333
500,0.115
505,0.1184167
510,0.1221667
515,0.1263333
520,0.131
525,0.13625
530,0.1420833
535,0.14875
540,0.1563333
545,0.1651667
550,0.1754167
555,0.1875
560,0.202
565,0.2195
570,0.241
575,0.268
580,0.3025833
585,0.3479167
590,0.4093333
595,0.4954167
600,0.62175
605,0.8180833
610,1.147833
615,1.7655
620,3.136417
625,7.35025
630,7.35025
635,3.136417
640,1.7655
645,1.147833
650,0.8180833
655,0.62175
660,0.4954167
665,0.4093333
670,0.3479167
675,0.3025833
680,0.268
685,0.241
690,0.2195
695,0.202
700,0.1875
705,0.1754167
710,0.1651667
715,0.1563333
720,0.14875
725,0.1420833
730,0.13625
735,0.131
740,0.1263333
745,0.1221667
750,0.1184167
755,0.115
760,0.1118333
765,0.109
770,0.1063333
775,0.1039167
780,0.1016667
785,0.136658
790,0.136658
795,0.136658
800,0.136658
805,0.136658
810,0.136658
815,0.136658
820,0.136658
825,0.136658
830,0.136658
835,0.136658
840,0.136658
845,0.136658
850,0.136658
855,0.136658
860,0.136658
865,0.136658
870,0.136658
875,0.136658
880,0.136658
885,0.136658
890,0.136658
895,0.136658
900,0.136658
905,0.136658
910,0.136658
915,0.136658
920,0.136658
925,0.136658
930,0.136658
935,0.136658
940,0.136658
945,0.136658
950,0.136658
955,0.136658
960,0.136658
965,0.136658
970,0.136658
975,0.136658
980,0.136658
985,0.136658
990,0.136658
995,0.136658
1000,0.136658
1005,0.136658
1010,0.136658
1015,0.136658
1020,0.136658
1025,0.136658
1030,0.136658
1035,0.136658
1040,0.136658
1045,0.136658
1050,0.136658
1055,0.136658
1060,0.136658
1065,0.136658
1070,0.136658
1075,0.136658
1080,0.136658
1085,0.136658
1090,0.136658
1095,0.136658
1100,0.136658
1105,0.136658
1110,0.136658
1115,0.136658
1120,0.136658
1125,0.136658
1130,0.136658
1135,0.136658
1140,0.136658
1145,0.136658
1150,0.136658
1155,0.136658
1160,0.136658
1165,0.136658
1170,0.136658
1175,0.136658
1180,0.136658
1185,0.136658
1190,0.136658
1195,0.136658
1200,0.136658
1205,0.136658
1210,0.136658
1215,0.136658
1220,0.136658
1225,0.136658
1230,0.136658
1235,0.136658
1240,0.136658
1245,0.136658
1250,0
1255,0
1260,0
1265,0
1270,0.136658
1275,0.136658
1280,0.136658
1285,0.136658
1290,0.136658
1295,0.136658
1300,0.136658
1305,0.136658
1310,0.136658
1315,0.136658
1320,0.136658
1325,0.136658
1330,0.136658
1335,0.136658
1340,0.136658
1345,0.136658
1350,0.136658
1355,0.136658
1360,0.136658
1365,0.136658
1370,0.136658
1375,0.136658
1380,0.136658
1385,0.136658
1390,0.136658
1395,0.136658
1400,0.136658
1405,0.136658
1410,0.136658
1415,0.136658
1420,0.136658
1425,0.136658
1430,0.136658
1435,0.136658
1440,0.136658
1445,0.136658
1450,0.136658
1455,0.136658
1460,0.136658
1465,0.136658
1470,0.136658
1475,0.136658
1480,0.136658
1485,0.136658
1490,0.136658
1495,0.136658
1500,0.136658
1505,0.136658
1510,0.136658
1515,0.136658
1520,0.136658
1525,0.136658
1530,0.136658
1535,0.136658
1540,0.136658
1545,0.136658
1550,0.136658
1555,0.136658
1560,0.136658
1565,0.136658
1570,0.136658
1575,0.136658
1580,0.136658
1585,0.136658
1590,0.136658
1595,0.136658
1600,0.136658
1605,0.136658
1610,0.136658
1615,0.136658
1620,0.136658
1625,0.136658
1630,0.136658
1635,0.136658
1640,0.136658
1645,0.136658
1650,0.136658
1655,0.136658
1660,0.136658
1665,0.136658
1670,0.136658
1675,0.136658
1680,0.136658
1685,0.136658
1690,0.136658
1695,0.136658
1700,0.136658
1705,0.136658
1710,0.136658
1715,0.136658
1720,0.136658
1725,0.136658
1730,0.136658
1735,0.1016667
1740,0.1039167
1745,0.1063333
1750,0.109
1755,0.1118333
1760,0.115
1765,0.1184167
1770,0.1221667
1775,0.1263333
1780,0.131
1785,0.13625
1790,0.1420833
1795,0.14875
1800,0.1563333
1805,0.1651667
1810,0.1754167
1815,0.1875
1820,0.202
1825,0.2195
1830,0.241
1835,0.268
1840,0.3025833
1845,0.3479167
1850,0.4093333
1855,0.4954167
1860,0.62175
1865,0.8180833
1870,1.147833
1875,1.7655
1880,3.136417
1885,7.35025
1890,7.35025
1895,3.136417
1900,1.7655
1905,1.147833
1910,0.8180833
1915,0.62175
1920,0.4954167
1925,0.4093333
1930,0.3479167
1935,0.3025833
1940,0.268
1945,0.241
1950,0.2195
1955,0.202
1960,0.1875
1965,0.1754167
1970,0.1651667
1975,0.1563333
1980,0.14875
1985,0.1420833
1990,0.13625
1995,0.131
2000,0.1263333
2005,0.1221667
2010,0.1184167
2015,0.115
2020,0.1118333
2025,0.109
2030,0.1063333
2035,0.1039167
2040,0.1016667
2045,0.136658
2050,0.136658
2055,0.136658
2060,0.136658
2065,0.136658
2070,0.136658
2075,0.136658
2080,0.136658
2085,0.136658
2090,0.136658
2095,0.136658
2100,0.136658
2105,0.136658
2110,0.136658
2115,0.136658
2120,0.136658
2125,0.136658
2130,0.136658
2135,0.136658
2140,0.136658
2145,0.136658
2150,0.136658
2155,0.136658
2160,0.136658
2165,0.136658
2170,0.136658
2175,0.136658
2180,0.136658
2185,0.136658
2190,0.136658
2195,0.136658
2200,0.136658
2205,0.136658
2210,0.136658
2215,0.136658
2220,0.136658
2225,0.136658
2230,0.136658
2235,0.136658
2240,0.136658
2245,0.136658
2250,0.136658
2255,0.136658
2260,0.136658
2265,0.136658
2270,0.136658
2275,0.136658
2280,0.136658
2285,0.136658
2290,0.136658
2295,0.136658
2300,0.136658
2305,0.136658
2310,0.136658
2315,0.136658
2320,0.136658
2325,0.136658
2330,0.136658
2335,0.136658
2340,0.136658
2345,0.136658
2350,0.136658
2355,0.136658
2360,0.136658
2365,0.136658
2370,0.136658
2375,0.136658
2380,0.136658
2385,0.136658
2390,0.136658
2395,0.136658
2400,0.136658
2405,0.136658
2410,0.136658
2415,0.136658
2420,0.136658
2425,0.136658
2430,0.136658
2435,0.136658
2440,0.136658
2445,0.136658
2450,0.136658
2455,0.136658
2460,0.136658
2465,0.136658
2470,0.136658
2475,0.136658
2480,0.136658
2485,0.136658
2490,0.136658
2495,0.136658
2500,0.136658
2505,0.136658
2510,0
2515,0
2520,0.136658
2525,0.136658
2530,0.136658
2535,0.136658
2540,0.136658
2545,0.136658
2550,0.136658
2555,0.136658
2560,0.136658
2565,0.136658
2570,0.136658
2575,0.136658
2580,0.136658
2585,0.136658
2590,0.136658
2595,0.136658
2600,0.136658
2605,0.136658
2610,0.136658
2615,0.136658
2620,0.136658
2625,0.136658
2630,0.136658
2635,0.136658
2640,0.136658
2645,0.136658
2650,0.136658
2655,0.136658
2660,0.136658
2665,0.136658
2670,0.136658
2675,0.136658
2680,0.136658
2685,0.136658
2690,0.136658
2695,0.136658
2700,0.136658
2705,0.136658
2710,0.136658
2715,0.136658
2720,0.136658
2725,0.136658
2730,0.136658
2735,0.136658
2740,0.136658
2745,0.136658
2750,0.136658
2755,0.136658
2760,0.136658
2765,0.136658
2770,0.136658
2775,0.136658
2780,0.136658
2785,0.136658
2790,0.136658
2795,0.136658
2800,0.136658
2805,0.136658
2810,0.136658
2815,0.136658
2820,0.136658
2825,0.136658
2830,0.136658
2835,0.136658
2840,0.136658
2845,0.136658
2850,0.136658
2855,0.136658
2860,0.136658
2865,0.136658
2870,0.136658
2875,0.136658
2880,0.136658
2885,0.136658
2890,0.136658
2895,0.136658
2900,0.136658
2905,0.136658
2910,0.136658
2915,0.136658
2920,0.136658
2925,0.136658
2930,0.136658
2935,0.136658
2940,0.136658
2945,0.136658
2950,0.136658
2955,0.136658
2960,0.136658
2965,0.136658
2970,0.136658
2975,0.136658
2980,0.136658
2985,0.1016667
2990,0.1039167
2995,0.1063333
3000,0.109
3005,0.1118333
3010,0.115
3015,0.1184167
3020,0.1221667
3025,0.1263333
3030,0.131
3035,0.13625
3040,0.1420833
3045,0.14875
3050,0.1563333
3055,0.1651667
3060,0.1754167
3065,0.1875
3070,0.202
3075,0.2195
3080,0.241
3085,0.268
3090,0.3025833
3095,0.3479167
3100,0.4093333
3105,0.4954167
3110,0.62175
3115,0.8180833
3120,1.147833
3125,1.7655
3130,3.136417
3135,7.35025
3140,7.35025
3145,3.136417
3150,1.7655
3155,1.147833
3160,0.8180833
3165,0.62175
3170,0.4954167
3175,0.4093333
3180,0.3479167
3185,0.3025833
3190,0.268
3195,0.241
3200,0.2195
3205,0.202
3210,0.1875
3215,0.1754167
3220,0.1651667
3225,0.1563333
3230,0.14875
3235,0.1420833
3240,0.13625
3245,0.131
3250,0.1263333
3255,0.1221667
3260,0.1184167
3265,0.115
3270,0.1118333
3275,0.109
3280,0.1063333
3285,0.1039167
3290,0.1016667
3295,0.136658
3300,0.136658
3305,0.136658
3310,0.136658
3315,0.136658
3320,0.136658
3325,0.136658
3330,0.136658
3335,0.136658
3340,0.136658
3345,0.136658
3350,0.136658
3355,0.136658
3360,0.136658
3365,0.136658
3370,0.136658
3375,0.136658
3380,0.136658
3385,0.136658
3390,0.136658
3395,0.136658
3400,0.136658
3405,0.136658
3410,0.136658
3415,0.136658
3420,0.136658
3425,0.136658
3430,0.136658
3435,0.136658
3440,0.136658
3445,0.136658
3450,0.136658
3455,0.136658
3460,0.136658
3465,0.136658
3470,0.136658
3475,0.136658
3480,0.136658
3485,0.136658
3490,0.136658
3495,0.136658
3500,0.136658
3505,0.136658
3510,0.136658
3515,0.136658
3520,0.136658
3525,0.136658
3530,0.136658
3535,0.136658
3540,0.136658
3545,0.136658
3550,0.136658
3555,0.136658
3560,0.136658
3565,0.136658
3570,0.136658
3575,0.136658
3580,0.136658
3585,0.136658
3590,0.136658
3595,0.136658
3600,0.136658
3605,0.136658
3610,0.136658
3615,0.136658
3620,0.136658
3625,0.136658
3630,0.136658
3635,0.136658
3640,0.136658
3645,0.136658
3650,0.136658
3655,0.136658
3660,0.136658
3665,0.136658
3670,0.136658
3675,0.136658
3680,0.136658
3685,0.136658
3690,0.136658
3695,0.136658
3700,0.136658
3705,0.136658
3710,0.136658
3715,0.136658
3720,0.136658
3725,0.136658
3730,0.136658
3735,0.136658
3740,0.136658
3745,0.136658
3750,0.136658
3755,0.136658
3760,0
3765,0
3770,0.136658
3775,0.136658
3780,0.136658
3785,0.136658
3790,0.136658
3795,0.136658
3800,0.136658
3805,0.136658
3810,0.136658
3815,0.136658
3820,0.136658
3825,0.136658
3830,0.136658
3835,0.136658
3840,0.136658
3845,0.136658
3850,0.136658
3855,0.136658
3860,0.136658
3865,0.136658
3870,0.136658
3875,0.136658
3880,0.136658
3885,0.136658
3890,0.136658
3895,0.136658
3900,0.136658
3905,0.136658
3910,0.136658
3915,0.136658
3920,0.136658
3925,0.136658
3930,0.136658
3935,0.136658
3940,0.136658
3945,0.136658
3950,0.136658
3955,0.136658
3960,0.136658
3965,0.136658
3970,0.136658
3975,0.136658
3980,0.136658
3985,0.136658
3990,0.136658
3995,0.136658
4000,0.136658
4005,0.136658
4010,0.136658
4015,0.136658
4020,0.136658
4025,0.136658
4030,0.136658
4035,0.136658
4040,0.136658
4045,0.136658
4050,0.136658
4055,0.136658
4060,0.136658
4065,0.136658
4070,0.136658
4075,0.136658
4080,0.136658
4085,0.136658
4090,0.136658
4095,0.136658
4100,0.136658
4105,0.136658
4110,0.136658
4115,0.136658
4120,0.136658
4125,0.136658
4130,0.136658
4135,0.136658
4140,0.136658
4145,0.136658
4150,0.136658
4155,0.136658
4160,0.136658
4165,0.136658
4170,0.136658
4175,0.136658
4180,0.136658
4185,0.136658
4190,0.136658
4195,0.136658
4200,0.136658
4205,0.136658
4210,0.136658
4215,0.136658
4220,0.136658
4225,0.136658
4230,0.136658
4235,0.1016667
4240,0.1039167
4245,0.1063333
4250,0.109
4255,0.1118333
4260,0.115
4265,0.1184167
4270,0.1221667
4275,0.1263333
4280,0.131
4285,0.13625
4290,0.1420833
4295,0.14875
4300,0.1563333
4305,0.1651667
4310,0.1754167
4315,0.1875
4320,0.202
4325,0.2195
4330,0.241
4335,0.268
4340,0.3025833
4345,0.3479167
4350,0.4093333
4355,0.4954167
4360,0.62175
4365,0.8180833
4370,1.147833
4375,1.7655
4380,3.136417
4385,7.35025
4390,7.35025
4395,3.136417
4400,1.7655
4405,1.147833
4410,0.8180833
4415,0.62175
4420,0.4954167
4425,0.4093333
4430,0.3479167
4435,0.3025833
4440,0.268
4445,0.241
4450,0.2195
4455,0.202
4460,0.1875
4465,0.1754167
4470,0.1651667
4475,0.1563333
4480,0.14875
4485,0.1420833
4490,0.13625
4495,0.131
4500,0.1263333
4505,0.1221667
4510,0.1184167
4515,0.115
4520,0.1118333
4525,0.109
4530,0.1063333
4535,0.1039167
4540,0.1016667
4545,0.136658
4550,0.136658
4555,0.136658
4560,0.136658
4565,0.136658
4570,0.136658
4575,0.136658
4580,0.136658
4585,0.136658
4590,0.136658
4595,0.136658
4600,0.136658
4605,0.136658
4610,0.136658
4615,0.136658
4620,0.136658
4625,0.136658
4630,0.136658
4635,0.136658
4640,0.136658
4645,0.136658
4650,0.136658
4655,0.136658
4660,0.136658
4665,0.136658
4670,0.136658
4675,0.136658
4680,0.136658
4685,0.136658
4690,0.136658
4695,0.136658
4700,0.136658
4705,0.136658
4710,0.136658
4715,0.136658
4720,0.136658
4725,0.136658
4730,0.136658
4735,0.136658
4740,0.136658
4745,0.136658
4750,0.136658
4755,0.136658
4760,0.136658
4765,0.136658
4770,0.136658
4775,0.136658
4780,0.136658
4785,0.136658
4790,0.136658
4795,0.136658
4800,0.136658
4805,0.136658
4810,0.136658
4815,0.136658
4820,0.136658
4825,0.136658
4830,0.136658
4835,0.136658
4840,0.136658
4845,0.136658
4850,0.136658
4855,0.136658
4860,0.136658
4865,0.136658
4870,0.136658
4875,0.136658
4880,0.136658
4885,0.136658
4890,0.136658
4895,0.136658
4900,0.136658
4905,0.136658
4910,0.136658
4915,0.136658
4920,0.136658
4925,0.136658
4930,0.136658
4935,0.136658
4940,0.136658
4945,0.136658
4950,0.136658
4955,0.136658
4960,0.136658
4965,0.136658
4970,0.136658
4975,0.136658
4980,0.136658
4985,0.136658
4990,0.136658
4995,0.136658
5000,0.136658
5005,0.136658

**Comment by Jonasvsl** [comment]
[longrain.csv](https://github.com/nens/threedi-api-qgis-client/files/8685911/longrain.csv)

**Comment by Jonasvsl** [comment]
[augustus2010.csv](https://github.com/nens/threedi-api-qgis-client/files/8685913/augustus2010.csv)

**Comment by ldebek** [comment]
@Jonasvsl It seems like there are some constrains for the rain timeseries endpoint. This is what I'm getting while I'm trying to upload rain data in chunks: `The first timestamp should be 0`.

**Comment by daanvaningen** [comment]
you can use offset to displace a chunk in time. So the first timestamp has to be 0, but to make the timeseries start at a specific time in the simulation you can use offset.

**Comment by leendertvanwolfswinkel** [comment]
Tested for mm/h and mm/timestep, with and without offset. It all works as it should!
