### ISSUE TITLE
Log in using API Key

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#366]
- [x] Allow users to set an API Key in the plugin settings
- [x] Store the API Key in the QGIS Password Manager (@caspervdw I assume we should store this key encrypted only, not as plain text?)
- [x] Log in using the API Key (please get in touch with @caspervdw for details)
- [ ] #371

**Comment by Patrick-Nijman** [comment]
The Personal API key management screens will be developed later on but the API end-points are already available.
Swagger:
/v3-beta/personalapikeys/ 

data:
{
  "scope": "*:readwrite",
  "name": "test_Key"
}

This will create an API key which can be used with API calls. 
Username: __key__
Password: API Key

With this you can perform API calls with an API-Key

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Changes might be tested on branch: https://github.com/nens/threedi-api-qgis-client/tree/personal_api_key_authorization . Redirecting to the website is not implemented, as wbesite is not available yet, so it might be good to move that bit to separate ticket for a time beign.

**Comment by leendertvanwolfswinkel** [comment]
Moved last bit to #371
Feature will remain on seperate branch (#369) until #371 is fixed

**Comment by leendertvanwolfswinkel** [comment]
Using api.3di.live, I get the following message
![image](https://user-images.githubusercontent.com/26224299/173317710-b57f9067-c9dd-4a88-866e-36f91355dcca.png)

Settings:
![image](https://user-images.githubusercontent.com/26224299/173317833-72769537-cd21-4492-8ad1-115c5c3bb809.png)
