### ISSUE TITLE
[3Di]: add 'only show own simulations' option to download results interface

### ISSUE THREAD

**Issue by Patrick-Nijman** [nens/threedi-api-qgis-client#368]
- [ ] https://github.com/nens/servicedesk-issue-only/issues/45

### Contact Details
Olof

### What happened?

When downloading your results, it would be nice to have an option to filter out all simulations by other users, just like in the management screens. 

![image](https://user-images.githubusercontent.com/73856313/161570914-e697b0d2-4ddf-41d3-a49b-69154b4ad132.png)
![image](https://user-images.githubusercontent.com/73856313/161570971-33357d02-c078-4c58-ae2a-b6e1ed446219.png)

**Comment by Patrick-Nijman** [comment]
@leendertvanwolfswinkel Kan jij deze inplannen / timeframen. Lijkt me een nice feature maar niet heel ingewikkeld om te maken. Maar ik kan het mis hebben 😄

**Comment by ldebek** [comment]
@leendertvanwolfswinkel `SimulationStatus` returned by `threedi-api-client` have no unique user ID which I could use to undoubtedly identify user which started the simulation. I could use `simulation_user_first_name` and `simulation_user_last_name` combination but I'm not sure that this combination will be unique?

**Comment by leendertvanwolfswinkel** [comment]
@ldebek I think that is fine, but we should make it explicit. I propose to make it an option "Filter on user name", with two fields "First name" and "Last name", prepopulated with the logged-in users First name and Last name.

Please also (re-)add the column "User name" to the table, which should show the `f"{simulation_user_first_name} simulation_user_last_name" to the downloadable results list view?

**Comment by leendertvanwolfswinkel** [comment]
@ldebek while you are at it, I have two additional wishes... Let me make a complete list including the stuff mentioned above:
- [ ] Add an option "Filter by user name", with two fields "First name" and "Last name", prepopulated with the logged-in users First name and Last name.
- [ ] (Re-)add the column "User name" to the table, which should show the `f"{simulation_user_first_name} simulation_user_last_name"
- [ ] Make the "Simulation name" column as wide as the longest name in the list
- [ ] When user double-clicks a row, start downloading it

Artist's impression:

<img width="918" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLy9jQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a0037e787a50f938f062fb588f149d7aae7b6e13/image.png" alt="image.png" />

**Comment by leendertvanwolfswinkel** [comment]
@ldebek love it, please merge
