### ISSUE TITLE
If user attempts to log in, but no valid API key is available, open the website where they can obtain this API key (@Patrick-Nijman does this website exist yet?)

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#371]
- Button should be next to "Set Personal API Key" button
- Clicking the button should open the website where they can obtain this API key (url: https://management.3di.live/personal_api_keys)

**Comment by ldebek** [comment]
Changes availabale on `pak_authorization` branch.
