### ISSUE TITLE
API Key Log-in improvements

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#372]
- [ ] No longer show the "log-in" dialog, just silently (attempt to) log in if API key is available
![image](https://user-images.githubusercontent.com/26224299/172644765-21c8a352-4ae9-47fb-8e56-bdca1956921c.png)
- [ ] If API key is not filled in, after showing the warning message, open the plugin settings dialog

**Comment by ldebek** [comment]
Changes availabale on `pak_authorization` branch.

**Comment by leendertvanwolfswinkel** [comment]
Tested
