### ISSUE TITLE
New schematisation from existing spatialite: improve raster handling

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#375]
- [x] Copy all referenced rasters, not only those referenced in v2_global_settings
- [x] If a raster file is not found, do not empty the attribute
- [x] If one ore more raster files are not found, give feedback about this to the user. "Warning: the following raster files where not found: {list of attribute: file names, e.g. dem_file: rasters\dem.tif; infiltration_capacity_file: infiltration.tif}"

**Comment by ldebek** [comment]
Changes available for testing on branch `improved_raster_handling`

**Comment by leendertvanwolfswinkel** [comment]
Tested; unfortunately with this dataset https://we.tl/t-7uO3Kd1IIo I get this error: 
![image](https://user-images.githubusercontent.com/26224299/177207840-a8d503af-8a02-4ffe-af3b-18b6bc335681.png)

On my machine the data is stored in `C:\Users\leendert.vanwolfswin\OneDrive - Nelen & Schuurmans\Documents 1\3Di\Hekerbeek drempel 40 cm\work in progress\schematisation`

**Comment by ldebek** [comment]
@leendertvanwolfswinkel I've pushed fix for this issue. Feel free to test it once again.

**Comment by leendertvanwolfswinkel** [comment]
ok issue is fixed. I did notice something else though. If I create a new schematisation from scratch, that schematisation becomes the active one and I get this popup:
![image](https://user-images.githubusercontent.com/26224299/177533268-0d615cc5-82b7-4380-bfee-c18c51a5bdd8.png)

If I create new schematisation from existing spatialite, the schematisation is not activated (and I also do not get the popup of course)

**Comment by leendertvanwolfswinkel** [comment]
@ldebek I'll make a new ticket for my previous comment. I'll close this ticket and merge the branch with master
