### ISSUE TITLE
Ask user before migrating spatialite

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#377]
Same implementation as https://github.com/nens/threedi-schematisation-editor/issues/50

**Comment by ldebek** [comment]
Changes on branch: https://github.com/nens/threedi-api-qgis-client/tree/migration_on_the_fly

**Comment by leendertvanwolfswinkel** [comment]
Tested. Excellent workflow. Please merge with master
