### ISSUE TITLE
Specific handling of SSL error

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#379]
The following error should be caught and a specific message should be shown to users:

![MicrosoftTeams-image (15)](https://user-images.githubusercontent.com/26224299/176410109-731a1b12-31cc-480c-87d3-b7cc3a857326.png)

Message text should be:
"An error occurred. This specific error is probably caused by issues with an expired SSL certificate that has not properly been removed by your operating system. Please ask your system administrator to remove this expired SSL certificate manually. Instructions can be found here: https://docs.3di.live/f_problem_solving.html#connecting-to-the-3di-api

Error details: {original error message}"

**Comment by ldebek** [comment]
Changes availabale on `pak_authorization` branch.

**Comment by leendertvanwolfswinkel** [comment]
I am afraid I can't test this, so I am closing it hoping it works as intended...
