### ISSUE TITLE
API Key GUI improvements

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#382]
The text doesn't fit the buttons:
![image](https://user-images.githubusercontent.com/26224299/177138480-2c656dfe-a8d3-4c13-9c56-6364c10061c9.png)

Proposal:
![image](https://user-images.githubusercontent.com/26224299/177138651-f496a748-14ff-44e8-abd0-091c88a29729.png)

**Comment by ldebek** [comment]
Done
