### ISSUE TITLE
New simulation in separate thread so that QGIS is not blocked

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#389]
Due to the recent extensions of the Simulation Wizard, starting a simulation may take quite a bit of time. This is especially the case when resources are being uploaded (e.g. initial water level rasters or lateral timeseries).

Also, the code for this part has become a bit lumpy (many things have been incrementally added to an initially short/simple part of the code).

Proposal to fix this:

- [x] Put "starting new simulation" in a seperate thread
- [x] Add a progress bar 
- [x] Clean up / improve the code structure

**Comment by ldebek** [comment]
Changes are available on `simulation_wizard_runner_refactoring` branch. **Please notice that they are quite deep, so extensive user testing is highly recommended.**

**Comment by leendertvanwolfswinkel** [comment]
@ldebek First tests give me the following error:

"** ERROR  : Boundary locations are present in schematisation, but some/all are missing values"

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Is it happening on master as well or just on branch with changes? And second thing - could you plese point me on model that you are using and/or share shcematisation with me, so I can check it out?

**Comment by leendertvanwolfswinkel** [comment]
I have tested it also on master; it works fine there. 

I will find an example that is accessible to you

**Comment by leendertvanwolfswinkel** [comment]
@ldebek Please use "Demo model 1d2d (Lutra)" on organisation "Lutra consulting" to reproduce this issue.

I started this simulation by just clicking next to the end of the simulation wizard (only changed the simulation name): https://api.3di.live/v3/simulations/101716/status/history/

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Issue is fixed now.

**Comment by leendertvanwolfswinkel** [comment]
Continued testing, found a new issue. When using custom rain, the following error is raised:

`3Di Models and Simulations : Error: expected str, bytes or os.PathLike object, not bool`

You can use this csv file as an example: 
[neerslag_t100_klimaat2050.csv](https://github.com/nens/threedi-api-qgis-client/files/10050546/neerslag_t100_klimaat2050.csv)

**Comment by leendertvanwolfswinkel** [comment]
Not related to this refactor, but could you please change the text "Load model" on the bottom-right button in the "Choose model and simulation template" dialog to "Next"?

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Issues should be fixed now.
