### ISSUE TITLE
Compatibility with schema version 208

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#398]
- [x] Set minimum schema version to 208
- [x] Upgrade the spatialite that is shipped with the plugin to schema version 208
- [x] In the New Schematisation wizard, on the last page, Remove "Table step size [m]"
- [x] When creating a new schematisation with a new spatialite, do no longer write the field `table_step_size_volume_2d`
- [x] Use `0.05` as default value for `table_step_size`. The field `maximum_table_step_size` does not need to be filled in.

**Comment by ldebek** [comment]
Fix available on branch: `compatibility_with_schema_208`

**Comment by leendertvanwolfswinkel** [comment]
Tested
