### ISSUE TITLE
Load repository

### ISSUE THREAD

**Issue by PeterPetrik** [nens/threedi-api-qgis-client#4]
Only Load web option implemented

- [ ] Load repository window
- [ ] Test for API
- [ ] Search web repositories (repository name search?)

![Screenshot 2020-02-25 at 09 19 37](https://user-images.githubusercontent.com/804608/75228167-f6d0e500-57af-11ea-8e53-7ca9fcdcffa3.png)

estimate 1 day

**Comment by DamnBack** [comment]
Implemented
