### ISSUE TITLE
Download gridadmin.h5 when downloading a revision

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#402]
When a user downloads a schematisation revision:
- Check if a threedimodel is available for this revision
- If so, download its gridadmin.h5 file to `{3Di working directory}\{schematisation}\{revision _n_}\grid` or `{3Di working directory}\{schematisation}\work_in_progress\grid`

**Comment by ldebek** [comment]
Changes available on branch: `gridadmin_files_handling_changes`

**Comment by leendertvanwolfswinkel** [comment]
It works, but somehow now I get this message when I start the download: 
![image](https://user-images.githubusercontent.com/26224299/197599105-441d349d-b22f-410d-b8ea-a165ed0ba333.png)

After clicking OK, downloading starts and everything works just fine

**Comment by ldebek** [comment]
@ldebek Ups... That were some debug-related leftovers. :) I removed them.

**Comment by leendertvanwolfswinkel** [comment]
@ldebek Tested again, works fine now :) please merge with master
