### ISSUE TITLE
Download gridadmin.h5 file to \grid when downloading simulation results

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#403]
When downloading simulation results, the `gridadmin.h5` file is now stored in the same directory as the `results_3di.nc`. This should still be the case for backward compatibility reasons. In addition to that, please _also_ store the `gridadmin.h5` in `{3Di working directory}\{schematisation}\{revision _n_}\grid`

**Comment by ldebek** [comment]
Changes available on branch: `gridadmin_files_handling_changes`
