### ISSUE TITLE
Dialog "Remove excess 3Di models" doesn't show in some cases

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#409]
I am not sure exactly under which circumstances this occurs. Some suspicions:
- If the schematisation has been renamed. What is also strange (and I think somehow related) is that the name of the local directory will still have the old name if you download the schematisation. There may also be a backend issue here?
- If there are threedimodels that are not valid

First thing to check is, which are the exact criteria for counting 3Di models for a schematisation in the backend, i.e. if the API says there are 3 threedimodels, how were these 3 counted? @jpprins1 please comment on this

**Comment by jpprins1** [comment]
There are two checks in place:

   ```
    # Maximum active ThreediModels per organisation check (based on contract)
        active_models_count = (1
            ThreediModel.objects.filter(
                revision__schematisation__owner=self.owner,
                disabled=False,
            )
            .exclude(is_valid=False)
            .count()
        )


# Raises following error
raise ValidationError(
                "Maximum number of active threedimodels for organisation "
                f"{self.owner.unique_id} is {contract_limit}."
            )
```

```
        # Maximum active ThreediModels per schematisation check
        active_models_count = (
            ThreediModel.objects.filter(
                revision__schematisation=self,
                disabled=False,
            )
            .exclude(is_valid=False)
            .count()
        )

# Raises following error
raise ValidationError(
                "Maximum number of active threedimodels for schematisation "
                f"{self.id} is "
                f"{self.threedimodel_limit}."
            )
```

Which of the two errors is raised?

**Comment by leendertvanwolfswinkel** [comment]
Some other remarks from @jpprins1:
 If a model is deleted, `disabled` becomes `False`. Only threedimodels that have `disabled=False` and `is_valid=True` are counted

**Comment by leendertvanwolfswinkel** [comment]
@ldebek you can reproduce it like this:
- Download schematisation Demo model 1d2d (Lutra), latest revision
- Replace the sqlite with this one 
[Demo model 1d2d (Lutra).zip](https://github.com/nens/threedi-api-qgis-client/files/10921239/Demo.model.1d2d.Lutra.zip)
- Upload revision, using 'Upload & process' option
- After the data has been uploaded, it will show the following error: `Maximum number of active threedimodels for schematisation`

**Comment by leendertvanwolfswinkel** [comment]
@ldebek It seems to work fine for testing against the schematisation-level limit. However, if the schematisation-level limit has not been reached, but the organisation-level limit _has_ been reached, I do not get a pop-up, but I do get an error later on in the process (when generating a threedimodel)

How to reproduce:
- We have created an organisation on staging for the purpose of testing this functionality, called 'test_leendert'. You should have received an email with an invitation for this organisation. This organisation has a limit of 2 threedimodels, and currently has 2 threedimodels.
- Download the schematisation 'Test organisation level maximum model count', latest revision
- Make a change to it, e.g. change `v2_global_settings.sim_time_step` to 6 seconds
- Upload a new revision, using the option 'upload and process'.

**Comment by leendertvanwolfswinkel** [comment]
In the popup for 'Maximum number of active 3Di models for *organisation*', it should show the models for all schematisations; it now only shows models for the active schematisation
![image.png](https://images.zenhubusercontent.com/62bedb7b667872a01ff3bdff/082e6a3f-d21c-40eb-997a-9fad7e82fcf6)
