### ISSUE TITLE
Remove raster checker

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#412]
`threedi_modelchecker` has been adapted (v 0.32) to include raster checks. Tasks for 3Di Models & Simulations:

- [x] Remove all UI elements related to the raster checker from the Upload wizard
- [x] Remove all code related to the raster checker 

No extra code should be required for the new raster checks to be performed (as long as `threedi_modelchecker` v0.32 or higher is available)

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Changes available for testing on branch: https://github.com/nens/threedi-api-qgis-client/tree/upload_wizard_checker_update
