### ISSUE TITLE
Error: `upload_file() got an unexpected keyword argument 'callback_func'`

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#416]
When uploading a revision, the following error occurs:

![image](https://user-images.githubusercontent.com/26224299/206020860-bc628df3-081d-4b1d-8021-2a012dd2d9b5.png)

This is most probably related to the simulation wizard refactor, because we tested the exact same actions with both versions (with vs. without simulation wizard refactor); in the version without the refactor, everything works just fine.

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Fix available on master branch.
