### ISSUE TITLE
Schematisation cannot be downloaded if make 3Di model failed

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#428]
How to reproduce:

- Make sure you do not have a local copy of schematisation "Demo model 1d2d (Lutra)"
- Download revision 4 of this schematisation

You will get this error:
![image](https://user-images.githubusercontent.com/26224299/210566848-51e0bc6d-3700-49c0-ad12-03a3dc210fff.png)

Please handle this case; attempt to download the gridadmin only if the revision has a threedimodel. I don't think the user needs to be informed about the gridadmin not being available, the download of the schematisation should be completed also if the gridadmin is not available.

**Comment by ldebek** [comment]
Fix available on master.
