### ISSUE TITLE
Check computational grid before upload

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#429]
Very similar to how the schematisation checker is part of the upload wizard. We have just removed the raster checker; in its place we could generate the computational grid and show any errors & warnings from that process in a table widget.

One possible issue I see with this is the location to write the gridadmin.h5 file to. In the working directory structure, its logical place would be `\work in progress\grid\gridadmin.h5`. However, if this file already exists in this location, it has to be overwritten, which may not be possible due to locks (file being in use). Easiest solution might be to attempt deleting the file and if it fails, write the gridadmin file to a temp directory

For logging messages from `threedigrid_builder`, you may have a look at this commit https://github.com/nens/ThreeDiToolbox/commit/88d3ea947d549495d426866daec96f0b326091a3

**Comment by caspervdw** [comment]
There is no reason for creating a gridadmin.h5; gridbuilder supports outputting the layers in-memory, so they may be converted directly to qgis layers (without having a file)

**Comment by leendertvanwolfswinkel** [comment]
I can't believe we **finally** have this feature. Great work. Please merge @ldebek !
