### ISSUE TITLE
Download gridadmin geopackage if available

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#438]
When downloading a schematisation revision, it is currently already checked if a valid model for this revision is available and if so, the gridadmin.h5 file is downloaded.

We now have a new endpoint from which the GIS representation of the gridadmin (in GeoPackage format) can be downloaded: 

`/v3/threedimodels/{id}/geopackage/download/`

Please download this file as well (to the same folder as the gridadmin.h5) if it is available. If it is not available, make sure the process continues without errors.

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Looks like a `threedi-api-client` with a new endpoint support is not released on PyPi yet. I would need it released first to finalize this ticket and prepare PR.

**Comment by leendertvanwolfswinkel** [comment]
The requested features all work as they should.
However I now realize I want some more and some changes (sorry for the feature creep...):
- [ ] Also download the gridadmin.gpkg when downloading results (download to the `grid` folder as well as to the `results` folder)
- [ ] When downloading a revision to the `work in progress` folder, the rasters and sqlite should be downloaded to that folder (because they are editable), but the `gridadmin.h5` and `gridadmin.gpkg` should be downloaded to `revision {nr}\grid` (because they are read-only)

**Comment by leendertvanwolfswinkel** [comment]
I downloaded a result and the gridadmin.gpkg was downloaded to the `results` folder, but not to the `grid` folder.

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Change requested above applied.
