### ISSUE TITLE
Simulation wizard: Improve UX for selecting breaches

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#440]
**User stories**
- I know the code or display name of the breach I want to open, and want to select that breach by typing the code/display name or by selecting it from a list
- I want to select a breach by clicking it on the map canvas. I want to see clearly which flowlines are valid and relevant
- I want to open several breaches in the same simulation (how relevant do you think this is @Jonasvsl ?)

**Which flowlines are valid and relevant as breach**
Valid: all flowlines with KCU type / line type 51, 52, 53, 54, and 55 are breachable. 
Relevant:
- The most relevant flowlines are the 'potential breach' flowlines (55), i.e. a flowline that `threedigrid_builder` generated because there a v2_potential_breach was schematised. These are also available in the gridadmin as `Breach` objects, with a point geometry.
- Less relevant are all other flowlines with KCU type 51-54

**UX**
In the Simulation Wizard, Breaches page, there should be the following options to select a breach:
- ComboBox with text search option; the combobox contains all the codes/display names (e.g. f"{code}: {display_name}") of the Breach objects in the gridadmin
- Tool to select from map canvas, with two options: 'Potential breach' (the default) or 'All 1D2D flowlines'. User clicks the button, map tool is activated and QGIS main window brought to the foreground. User clicks on a breach point or 1D2D flowline and simulation wizard is brought to the foreground.

**Technical consequences**
The simulation wizard will need to have access to the breaches and the flowlines. These could be downloaded as GeoJSON, or the gridadmin geopackage could be used for this. I propose to download the gridadmin GPKG (to its proper location in the directory structure, i.e. `/bla/bla/grid/gridadmin.gpkg`) and use the layers from there. This would also require that exporting breaches is added to the "export to geopackage" function of `threedigrid`.

**API call**
The endpoint `/v3/simulations/{simulation_pk}/events/breaches/` has changed: a parameter `line_id` has been added. This should now be used instead of the `potential_breach` parameter (which is still there for backward compatibility only). The line_id is the `id` of a line in the gridadmin.

**Comment by leendertvanwolfswinkel** [comment]
@Jonasvsl @caspervdw feedback please :)

**Comment by caspervdw** [comment]
This sounds good! Getting the breaches/flowlines from the gridadmin is indeed the best option.

**Comment by Jonasvsl** [comment]
@leendertvanwolfswinkel 

- I want to open several breaches in the same simulation (how relevant do you think this is @Jonasvsl ?)

This is relevant enough to have it as a possibility. It is not the most common thing to do, but in case someone wants this we do not want to chase them towards scripting

Other remarks:
- Do potential breaches based on a exchange line have a display or code name?

**Comment by ldebek** [comment]
@leendertvanwolfswinkel @Overmeen 
Few questions/request to wrap new UX functionality:
1. Is layer with `Breach` objects already included in `gridadmin.gpkg` file? If so - could you please provide me an example model with them (couldn't find such so far)
2. Which fields from the `Flowline` layer should I use to populate ID of the breach, suration till max depth, discharge coefficients, initial width and max breach depth?
3. While selecting multiple breaches - should it be possible to select them via Breach ID combobox as well?
4. While selecting multiple breaches - should it be possible to select features from both source layers - Breach and Flowline layers?

**Comment by leendertvanwolfswinkel** [comment]
ID of the breach, --> source_table_id in the flowline layer = id in schematisation = content_pk in the geojson (To get the potential breach from the geojson use the content_pk parameter to filter the potential breaches endpoint: /potential_breaches/?connected_pnt_id={content_pk})
duration till max depth --> same logic as currently implemented, i.e. fetch from simulation template if applicable
discharge coefficients --> same logic as currently implemented, i.e. fetch from simulation template if applicable
initial width --> same logic as currently implemented, i.e. fetch from simulation template if applicable
max breach depth --> if it is in the simulation template, fetch it from there. otherwise, you have the option to use the api to get this value (maximum_breach_depth via the /v3/threedimodels/{threedimodel_pk}/potentialbreaches/ endpoint) OR use threedigrid to get the `levbr` attribute from the breaches

> Is layer with Breach objects already included in gridadmin.gpkg file? If so - could you please provide me an example model with them (couldn't find such so far)

The breaches are in the layer "flowline", filter on `line_type=55`

> Which fields from the Flowline layer should I use to populate ID of the breach, duration till max depth, discharge coefficients, initial width and max breach depth?

- ID of the breach --> source_table_id in the flowline layer = id in schematisation = content_pk in the geojson (To get the potential breach from the geojson use the content_pk parameter to filter the potential breaches endpoint: /potential_breaches/?connected_pnt_id={content_pk})
- duration till max depth --> same logic as currently implemented
- discharge coefficients --> same logic as currently implemented
- initial width --> same logic as currently implemented
- max breach depth --> same logic as currently implemented I think? If somewhere in this logic the `levbr` from the geojson is used, the best option to replace that is probably to use the api to get this value (maximum_breach_depth via the /v3/threedimodels/{threedimodel_pk}/potentialbreaches/ endpoint)

> While selecting multiple breaches - should it be possible to select them via Breach ID combobox as well?

Yes

> While selecting multiple breaches - should it be possible to select features from both source layers - Breach and Flowline layers?

As mentioned above, the breaches are a subset of Flowlines (with line_type=55). So I think we can use a single layer and only change the the behaviour of the map tool as in the criteria it uses to select/ignore a feature?

**Comment by leendertvanwolfswinkel** [comment]
Test feedback:
- [ ] Move “Remove selected breach” to the bottom
img width="575" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGZkQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ce8db113b7fad7c0d2f17ce484b5ebcb1a3b5e3/image.png" alt="image.png" />
- [ ] Please use these stylings for the potential breaches and 1D2D flowlines: [Style.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGpkQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85b117b1db82b8ad4e1ea49483313ed23176fc37/Style.zip)
- [ ] Only load the required layers after the user has checked the “breaches” box and clicked Next
- [ ] Make sure the required layers are always removed when the simulation wizard closes, whether it is by starting the simulation or cancelling
- [ ] Can we use one button “Pick from map”? So that users on either of the two layers?
- [ ] The filtering for the 1D2D flowline should be `line_type in (51, 52, 53, 54)`
- [ ] Please display the breaches in the dropdown list as “{id} | {code} | {display_name}”
- [ ] I defined a breach but it is not used in the simulation https://api.3di.live/v3/simulations/222297/events/
