### ISSUE TITLE
Simulation Wizard: add time zone explainer for 'radar rain'

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#452]
If user selects 'radar rain', add a label with the following explainer text:

"Radar rain uses the time zone Central European Time (CET). Make sure you select this same time zone for the start of your simulation on the _Duration_ page to avoid confusion."

Assuming that #263 is also implemented

**Comment by Overmeen** [comment]
Tested and it works:

![image](https://github.com/nens/threedi-api-qgis-client/assets/84539501/eacd7d8e-6c69-4c4a-8643-bc1e618f406e)
