### ISSUE TITLE
wrong simple infiltration settings are used when multiple records exist TOPDESK 2302 0168 

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#463]
Servicedesk 2302 0168 simple infiltration id is not working in global setting?

I think there is a bug for simple infiltration id in globalsetting.

I have 2 model below using simple infiltration id =2 and 3, but the model still only take simple infiltration id=1 as the infiltration raster.

schematization information:
using simple infiltration id=3:
https://management.3di.live/schematisations/5777/46554
using simple infiltration id=2:
https://management.3di.live/schematisations/5777/46553

Could you check this for me?
Please also check if this same problem exists with other settings tables that reference rasters

**Comment by ldebek** [comment]
@leendertvanwolfswinkel `Schematisation not found. It is possible that it exists but you are not authorized to view this schematisation because it belongs to an organisation that you have no access rights for it.` Could you please double check that?

**Comment by leendertvanwolfswinkel** [comment]
@ldebek we are currently reworking the 3Di database schema and this ticket will not be relevant anymore after that.

Closing it
