### ISSUE TITLE
Simulation wizard: Improve Laterals page

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#467]
The current UI does not correspond with the possible use cases for laterals. Proposed UI:

![image.png](https://images.zenhubusercontent.com/62bedb7b667872a01ff3bdff/78e37a5c-ada2-43a0-a5a9-6829817ed223)

- [x] The whole group "1D laterals" should be disabled if there is no 1D in the threedimodel
- [x] "[ ] Use 1D laterals from simulation template" should be disabled if there are no 1D laterals in the simulation template
- [x] "[ ] Use 1D laterals from simulation template" should be enabled and checked if there are 1D laterals in the simulation template

- [x] The whole group "2D laterals" should be disabled if there is no 2D in the threedimodel
- [x] "[ ] Use 2D laterals from simulation template" should be disabled if there are no 2D laterals in the simulation template
- [x] "[ ] Use 2D laterals from simulation template" should be enabled and checked if there are 2D laterals in the simulation template

**Comment by leendertvanwolfswinkel** [comment]
@leendertvanwolfswinkel Check if units in spatialite are converted from minutes to seconds somehow? There was a ticket for this (weird vague thing)

**Comment by hoanphungt** [comment]
@leendertvanwolfswinkel where can I find the laterals page?

**Comment by hoanphungt** [comment]
@leendertvanwolfswinkel is it possible to select both 1d laterals and 2d laterals or only one of them is allowed? Previously, there is a dropdown to select 1d or 2d laterals so I thought only one of them can be selected at one time.

**Comment by leendertvanwolfswinkel** [comment]
@hoanphungt this is one of the main reasons to re-implement this page. It is a perfectly valid option to have both 1D and 2D laterals in your simulation, but the current UI implementation won't allow you to do this

**Comment by hoanphungt** [comment]
For this bullet: 

> - The whole group "1D laterals" should be disabled if there is no 1D in the threedimodel

How do I know if there is no 1D / 2D in the 3di model?

**Comment by leendertvanwolfswinkel** [comment]
@hoanphungt 1: if the user says "from template", it should be exactly the same as the template. So both the `events.laterals` and the `events.filelaterals`. 
2: Let's make our lives a bit simpler and remove this choice. The behaviour should just be that if the user checks both the "Use laterals from simulation template" and "Upload laterals" option, the uploaded laterals are added to the ones from the simulation template. You can just post to the same endpoint multple times for laterals, iirc.

**Comment by leendertvanwolfswinkel** [comment]
@hoanphungt I tested it and have the following feedback:

- [ ] When checking the "interpolate" box for 1D laterals, I get the following error:

```
TypeError: 'str' object does not support item assignment 
Traceback (most recent call last):
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_models_and_simulations\widgets\simulation_wizard.py", line 635, in interpolate_changed
    val["interpolate"] = interpolate
TypeError: 'str' object does not support item assignment
```
- [ ] The CSV file for 2D laterals should include a geometry. QGIS has several options for exporting to CSV with geometry. I suggest to use WKT format in WGS84 (EPSG:4326), because this is also what the API wants I think? The file that users can export in this way would look like this:

**Comment by hoanphungt** [comment]
@leendertvanwolfswinkel 
I fixed both errors. Could you please try again?

**Comment by hoanphungt** [comment]
The 2d laterals file should have columns in the following order:

X Y type id timeseries

**Comment by hoanphungt** [comment]
@leendertvanwolfswinkel this issue can be tested again on the `master` branch

**Comment by leendertvanwolfswinkel** [comment]
@hoanphungt one more minor design issue. I noticed that the "1D laterals" header looks different (I think just smaller font size) than the 2D laterals header. Please make them both the same as the 2D laterals header

![image](https://github.com/nens/threedi-api-qgis-client/assets/26224299/270f4bb0-1d88-4555-8472-d18dd9a6ccb3)

**Comment by hoanphungt** [comment]
> @hoanphungt I have tested again. I am now able to upload both 1D and 2D laterals in the same simulation.
> 
> However, my input is:
> 
> * 3 2D laterals (IDs 1, 2, 3)
> * 4 1D laterals (IDs 1, 2, 3, 4)
> 
> What the API says it has received:
> 
> * 3 2D laterals (ID 1, 2, 3)
> * 1 1D lateral (ID 4)
> 
> So the 1D laterals with IDs 1, 2, and 3 are missing.
> 
> Model: Akersloot (Leendert) #3 1D laterals CSV: [laterals_1d.csv](https://github.com/nens/threedi-api-qgis-client/files/15333868/laterals_1d.csv)
> 
> 2D laterals CSV: [laterals_2d_x_y_id_timeseries_wgs84.csv](https://github.com/nens/threedi-api-qgis-client/files/15333872/laterals_2d_x_y_id_timeseries_wgs84.csv)

It seems that laterals 1d and 2d can have the same id indeed. I didn't know about it. Can you test again in this PR: https://github.com/nens/threedi-api-qgis-client/pull/555?

**Comment by leendertvanwolfswinkel** [comment]
@hoanphungt tested it again and it works as expected. Please also fix the minor design issue mentioned in my previous comment and merge to master

**Comment by hoanphungt** [comment]
@leendertvanwolfswinkel I don't have the minor design issue that you mentioned so that's strange.
