### ISSUE TITLE
Add page "Generate saved state"

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#473]
Give user options for how they want to generate the saved state, exposing the possibilities available in the API

UI:
![image.png](https://images.zenhubusercontent.com/62bedb7b667872a01ff3bdff/c6425d46-7eb0-400f-a4b4-9edac0fbbea5)

The first two options should use the endpoint `/v3/simulations/{simulation_pk}/create-saved-states/timed/`

The last option should use the endpoint 
`/v3/simulations/{simulation_pk}/create-saved-states/stable-threshold/`

**Comment by ldebek** [comment]
`stable-threshold` saved state creation can be tested after fixing backend issue: https://github.com/nens/threedi-api/issues/1980

**Comment by Overmeen** [comment]
I have tested ''After a specified time'' functionality successfully. 

https://api.3di.live/v3/simulations/145258/events/ - > generate timed saved state
https://api.3di.live/v3/simulations/145259/events/ - > apply timed saved state

**Comment by leendertvanwolfswinkel** [comment]
@ldebek I made a mistake, the unit for water level should be `m`, not `m MSL`. Please correct this
