### ISSUE TITLE
Simulation wizard: "post-processing in Lizard" is not stored or read from simulation template correctly

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#481]

**Comment by ldebek** [comment]
@Overmeen Fix for your issue was pushed on a branch.

**Comment by Overmeen** [comment]
It works. However, I notice a small issue with parameters of the Damage estimation.

The input in my base simulation:
![image](https://github.com/nens/threedi-api-qgis-client/assets/84539501/71c72cda-9991-459f-9b17-2a4376cb1d96)


I start a simulation from this template and see post-processing is checked, perfect.
![image](https://github.com/nens/threedi-api-qgis-client/assets/84539501/c592afa3-a4ba-4a57-abb9-c23ecbb78f21)


The input for this simulation is now:
![image](https://github.com/nens/threedi-api-qgis-client/assets/84539501/5e52ba32-8064-4074-9178-e849e4610618)


The parameters "Cost type", "Flood month" and "Inundation period" are identical. However, the parameters "Repair time infrastructure" and "Repair time buildings" are different.

**Comment by ldebek** [comment]
@Overmeen Added changes, which should solve that issue.
