### ISSUE TITLE
"New schematisation" wizard: check if DEM and friction files actually exist

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#483]
On the last page of the wizard:
If user has chosen a DEM and/or friction file and clicks "Create Schematisation", please check if the files exist and are .tif / .tiff files. If not, show message "Chosen DEM file does not exist or is not a GeoTIFF (.tif or .tiff)" /  "Chosen friction file does not exist or is not a GeoTIFF (.tif or .tiff)"

Screenshots from a video a user sent us:

![image.png](https://images.zenhubusercontent.com/62bedb7b667872a01ff3bdff/9bbc82c2-f518-45ae-a749-60e5fa17def0)

![image.png](https://images.zenhubusercontent.com/62bedb7b667872a01ff3bdff/04dbea20-9048-44ba-b135-c7125235bc37)

**Comment by ldebek** [comment]
@leendertvanwolfswinkel I think that the cleanest option would be just to set the those line edits read only and selection would require using `...` button - what's you opinion?

**Comment by Overmeen** [comment]
The behavior is not entirely as expected. 

In case a "Global 2D friction coefficient" is set to a (non-zero) value and the "Friction file" field is left empty, the user meant to add the global value. There should not be a pop-up message indicating the friction file does not exist.

![image](https://github.com/nens/threedi-api-qgis-client/assets/84539501/17877e4d-0ce6-446b-92c7-b3220cd422e5)
![image](https://github.com/nens/threedi-api-qgis-client/assets/84539501/5bbb0a5a-6711-4cf5-be1e-555c38fd27fa)


The behavior should be:

- If "Friction file" field is empty and "Global 2D friction coefficient" is set to a (non-zero) value > create schematisation with Global value
- If "Friction file" field is empty and "Global 2D friction coefficient" is empty or zero > pop-message "'Global 2D friction coefficient' value has to be greater than 0
- If "Friction file" field is not empty > check for file existence and validity file extension > if ok, create schematisation with friction file. If not, pop-up message "Chosen friction file does not exist or is not a GeoTIFF (.tif or .tiff)"

**Comment by ldebek** [comment]
@Overmeen Changes in the validation rules applied.

**Comment by ldebek** [comment]
Changes applied.
