### ISSUE TITLE
Saved states are used even if the option is disabled (2307 0130)

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#484]
How to reproduce:

Use the simulation wizard to run a simulation with this model: `Demo model 1d2d (Lutra) #22`. Use initial conditions, but do not check 'use saved state'. The simulation should not use the saved state, but is does (see e.g. `api.3di.live/v3.0/simulations/138971/events/`

**Comment by ldebek** [comment]
@Overmeen Feel free to test the fix for this issue located on branch: https://github.com/nens/threedi-api-qgis-client/tree/issue_484

**Comment by Overmeen** [comment]
Tested and it works: https://api.3di.live/v3/simulations/143152/events/

However, I've used the same model as Leendert did (https://api.3di.live/v3/threedimodels/55483/) for testing and I received the following message when creating a simulation: 

`2023-08-17T11:58:35     CRITICAL    3Di Models and Simulations : Error: unhashable type: 'InitialWaterlevel'`

I've also tested starting a simulation from this model with version 3.5.2 of the plug-in and I do not receive this message.

**Comment by ldebek** [comment]
@Overmeen Error should be gone now. :)
