### ISSUE TITLE
Implement schematisation descriptions

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#493]
We want to start using descriptions on a _Schematisation_ level. The description is stored in and read from the `meta` property of a schematisation (`"meta": {"description": "my very cool description"},`). Currently, the meta property of schematisations do not yet contain this key, so take this into account.

Please implement this in the following components:
- [ ] New schematisation wizard, first page, between 'New schematisation name' and 'Tags', add 'Description'. The grey hint-text in the text input widget should read 'Concise description of your schematisation (optional)'
- [ ] Download schematisation dialog, remove the 'slug' column and replace it by a 'description' column

**Comment by leendertvanwolfswinkel** [comment]
@ldebek I tested this. The New schematisation wizard changes work as expected.
The download schematisation dialog has a "description" column, but does not display the schematisation description.

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Fix for the issue pushed.

**Comment by leendertvanwolfswinkel** [comment]
Perfect, please merge
