### ISSUE TITLE
Upload new revision wizard: Make "available schematisation revisions clearly read-only

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#496]
Users can now select an item in the table that shows "Available schematisation revisions". This makes them think that they need to make a choice here. Please change the look of this table to make it clear that it is read only. If possible, also make it impossible to select rows.

**Comment by emielverstegen** [comment]
Above the list there is the text "Available schematisation revisions". Maybe if you change this into "Current schematisation revisions" or something of that order, in combination with changing the looks of the list, it is even more clear.
