### ISSUE TITLE
Download results: Remove slashes from simulation name

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#497]
The path to which the results are stored includes the simulation name. If the simulation name is "Mag-Asawang #12 - Asawang Q increasing stepwise 100-800 m3/s", this creates problems. Please replace all "/" and "\" in the simulation name by "-" when making the path.

**Comment by ldebek** [comment]
@leendertvanwolfswinkel  Changes applied . Changes required in the Lizard plugin (issue #530 ) are available for testing here: https://github.com/nens/lizard-qgis-plugin/tree/issue_530
