### ISSUE TITLE
Simulation wizard: Rain "Stop after" value is not read correctly from simulation template

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#498]
This simulation template has a constant rain event that starts after 1 hour and stops after 2 hours: https://management.3di.live/simulations/153434

But when loaded in the Simulation Wizard, it says "stop after 1 hour":

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaDc4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4ef767dcd92503d9eff24abef2dae5215c67323a/image.png)

**Comment by ldebek** [comment]
@leendertvanwolfswinkel In the current implementation `stop after` should be meant as a duration of  the rain counted since "start after" time.  Would you like to change it in a way that it will be reffered as a period of the simulation duration?

**Comment by leendertvanwolfswinkel** [comment]
Ok wow I have always misunderstood this than. And all other users as well.

Easiest fix would be to simple change the text to "Rain duration" I guess

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ldebek** [comment]
@leendertvanwolfswinkel That's probably the cleanest and easiest option. Same should be applied to wind, right?

**Comment by ldebek** [comment]
@leendertvanwolfswinkel I double checked again, and I was wrong in my comment yesterday - stop after indeed reffers to the simulation duration and there is a bug in the way of reading template data. Sorry for the confusion.

**Comment by leendertvanwolfswinkel** [comment]
tested, can be merged 👍
