### ISSUE TITLE
Simulate window

### ISSUE THREAD

**Issue by PeterPetrik** [nens/threedi-api-qgis-client#5]
- [ ] Pinging the server for running simulations
- [ ] New simulation 
- [ ] Pause simulation
- [ ] Tests

![Screenshot 2020-02-25 at 09 21 55](https://user-images.githubusercontent.com/804608/75228352-49120600-57b0-11ea-870d-4af05ff9d5f5.png)

estimate 2 days

**Comment by DamnBack** [comment]
Implemented
