### ISSUE TITLE
Do not display this message if no schematisation is loaded

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#526]
<img width="592" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjNUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea14a9e2c39d28af5de999c2ce5102d35ef98820/image.png" alt="image.png" />

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Can't reproduce it. There is a check for loaded schematisation already implemented and it works for me just fine. Could you please double check this issue?

**Comment by leendertvanwolfswinkel** [comment]
The point is that this message is displayed also if no schematisation has been loaded with the schematisation editor at all; I think it should be shown only if a **different** schematisation is loaded

**Comment by leendertvanwolfswinkel** [comment]
@ldebek have you seen my comment above? Does this make it more clear what the issue is?

**Comment by leendertvanwolfswinkel** [comment]
@ldebek please merge
