### ISSUE TITLE
Inherit simulation templates from previous 3Di model

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#529]
The endpoint `/v3/schematisations/{schematisation_pk}/revisions/{id}/create-threedimodel/` has an argument `inherit_from_previous_revision`. 

Change page 3 of the Upload wizard

- [x] Remove the buttons "Upload only" and "Upload and process"
- [x] Add checkbox "Upload schematisation revision" -- Checked and disabled (cannot be unchecked)
- [x] Add checkbox "Make 3Di model" -- Checked and enabled (can be unchecked)
- [x] Add checkbox "Inherit simulation templates from previous revision" -- Checked and enabled (can be unchecked)
- [x] If "Make 3Di model" is unchecked, uncheck and disable "Inherit simulation templates from previous revision"
- [x] If "Make 3Di model" is checked, check and enable "Inherit simulation templates from previous revision"

When user clicks "Start upload":
- [x] If "Make 3Di model" is checked: same behaviour as currently for "Upload and process"
- [x] If "Inherit simulation templates from previous revision" is checked: call `/v3/schematisations/{schematisation_pk}/revisions/{id}/create-threedimodel/` with `inherit_from_previous_revision = True`

**Comment by leendertvanwolfswinkel** [comment]
Feedback:
- If I make the dialog larger in the vertical direction, the checkboxes are spread out over the bottom part of the page (see image below). I'd rather have the "select files" and "describe the changes you upload" boxes grow and the checkboxes remain in a compact way. I think this can be achieved by adding one or more spacers, if you have trouble with this @ldebek can probably advice you
- Don't use bold for the checkbox label text
<img width="688" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzRXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--118f3c3882397b3d8246daa12fe617370d721de4/image.png" alt="image.png" />

**Comment by hoanphungt** [comment]
@leendertvanwolfswinkel it could be that the threediapi wheel needs to be updated. I don't find in the readme how I can update it though. Do you know anyone that I can ask about it? Maybe Lukasz?

**Comment by hoanphungt** [comment]
@leendertvanwolfswinkel  I updated the threedi-api wheel and fixed your comments. Could you test it again?

**Comment by leendertvanwolfswinkel** [comment]
@hoanphungt I tested it again (on staging), but unfortunately I get a new error: <img width="756" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTAvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5f5504eb68c26b1b2368d7d2c79191e78c1d31b0/image.png" alt="image.png" />

**Comment by hoanphungt** [comment]
The error: Could not copy simulation template ... to threedimodel ... due to Bad Request is apparently a backend issue. @daanvaningen is working on it.

**Comment by daanvaningen** [comment]
yesterday I created a production hotfix to (hopefully) solve this. We think it's a timing issue in the worker. Can you please check if the hotfix worked?

**Comment by hoanphungt** [comment]
@daanvaningen 
it seems to work for me now:

![Screenshot from 2024-04-10 10-47-27](https://github.com/nens/threedi-api-qgis-client/assets/43402556/09b93cfc-2a69-4b2d-833f-b16955ddcbd7)

**Comment by leendertvanwolfswinkel** [comment]
@hoanphungt My test was less successful :( <img width="898" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEpVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d76be666223c1fe36f3b2cee985efe7f9158179b/image.png" alt="image.png" />

**Comment by hoanphungt** [comment]
@leendertvanwolfswinkel It said "Internal server error while trying to trigger simulation-template clone.", so I don't think it's a problem with the plugin.

**Comment by hoanphungt** [comment]
I tested it again. Something happened in the backend and sometimes it works, sometimes not. Maybe @daanvaningen can take a look further to see what goes wrong here.

**Comment by daanvaningen** [comment]
hotfixed it on prod, can you please check again?

**Comment by hoanphungt** [comment]
@daanvaningen I still got the same error, but it's a TypeError in sentry:

https://nens.sentry.io/issues/5203987391/?project=1496858&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=0

**Comment by daanvaningen** [comment]
Ah I thought you could do `asyncio.sleep(None)` but this gives a type error. Although I also wonder why the ThreediModel has not become valid in the meantime..
I hotfixed the error op production

**Comment by hoanphungt** [comment]
@leendertvanwolfswinkel can you test again? I tested again but run into an exception that the threedimodel is not valid: https://nens.sentry.io/issues/5205286351/?project=1496858&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=0

> Could not inherit simulation templates because ThreediModel is not valid

Although, for this schematisaion: bug_raster_exists, it created a new 3di model successfully.

**Comment by daanvaningen** [comment]
I've found the issue: inherit simulation templates task is dependent on a valid threedimodel, but this is not explicitly stated so in our task logic: The completion of the make geojson task is needed for a valid threedimodel but the inherit simulation template task is not directly linked to it. So if the geojson task takes too long the inherit task can't complete. I will let you know when I have a fix

**Comment by daanvaningen** [comment]
hotfixed it on prod

**Comment by hoanphungt** [comment]
@daanvaningen It's working now. Thanks for the fix :)
