### ISSUE TITLE
Include Water Quality in Simulation Wizard 

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#531]
- [ ] #534
- [ ] #535
- [ ] #536
- [ ] #537
- [ ] #538

**Comment by hoanphungt** [comment]
This looks more like an epic inside the Basic WQ epic to me than an issue. Some of the issues mentioned above (534 and 538) are already included in the Basic WQ epic.

**Comment by leendertvanwolfswinkel** [comment]
Ah yes you are right, sorry. I have added the other tickets to the epic as well and will close this one
