### ISSUE TITLE
Simulation wizard: Add substance concentrations to boundary conditions page

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#536]

**Comment by leendertvanwolfswinkel** [comment]
@hoanphungt I tested it and works well when I upload both the boundary condition time series itself **and** the substance concentration time series. But it does not work when I use the boundary conditions from the template and add the substance concentrations to them. How diffifcult would it be to also make that work? If it is to difficult, we could make a separate ticket and do that later. But then we need to disable the concentrations upload widgets if no CSV has been chosen for the boundary conditions yet (separate logic for 1D and 2D of course)


 happens** if you use boundary conditions from template, but upload substance concentrations?

**Comment by hoanphungt** [comment]
@leendertvanwolfswinkel Can you test again using template boundary conditions? I made it work and pushed a new commit to the connected PR.
