### ISSUE TITLE
Simulation wizard: use started_from = "modeller_interface" to simulations

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#556]
There is a new `started_from` field. Possible choices: ["api", "live_site", "modeller_interface"]. Can be set on simulation resource and via from-template endpoint. Please use this field and (obviously) use "modeller_interface" as value.

At this moment (21-05-2024) this is available on staging only

**Comment by leendertvanwolfswinkel** [comment]
@ldebek this probably required an upgrade of threedi-api-client? I got this error:

```
2024-06-03T11:13:39     CRITICAL    3Di Models and Simulations : Error: __init__() got an unexpected keyword argument 'started_from'
```

**Comment by ldebek** [comment]
@leendertvanwolfswinkel It seems that `started_from` is not implemented in the `threedi-api-client`  repo (master branch). Could you please double check it?

**Comment by leendertvanwolfswinkel** [comment]
@ldebek You were right; a new version (4.1.7) has just been released to PyPI

**Comment by ldebek** [comment]
@leendertvanwolfswinkel `threedi-api-client` updated to version 4.1.7

**Comment by leendertvanwolfswinkel** [comment]
@ldebek please merge :)
