### ISSUE TITLE
Simulation wizard: Boundary conditions: Let user choose units for uploaded substance concentration time series

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#577]
My model (Demo Dijkring 87-1) has both 1D and 2D boundary conditions. I want to use the boundary conditions from the template, and add substance concentrations to the 2D boundary conditions. However, my CSV file has time units in minutes, while the simulation template (by definition) has time units in seconds. So I get the error that the timesteps do not match.

Please add a units widget for each substance concentration CSV file that I upload, so that the time units can be converted to seconds before comparing them to the timeseries in the template.

**Comment by hoanphungt** [comment]
@leendertvanwolfswinkel could you also test this issue?

**Comment by leendertvanwolfswinkel** [comment]
@hoanphungt tested, please merge :)
