### ISSUE TITLE
"Stop after" not read correctly from the template if start after is 0

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#616]
How to reproduce:
- Load 3Di model "Bomenbuurt (RHDHV) #2", simulation template "Bomenbuurt test start after 0h / stop after 1h"
- Click next to reach the page "Precipitation"
- The value for "stop after" is 0 instead of 1

This is very similar to the issue that was fixed in nens/threedi-api-qgis-client#498

I tested also the case in that ticket (start after 1h, stop after 2h); that did not cause any trouble

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Just relized that I pushed fix for the issue directly to master... my mistake and sorry for that. However change was small and simple, so it shouldn't break anything. :)

**Comment by leendertvanwolfswinkel** [comment]
@ldebek, tested it and it works as it should!
