### ISSUE TITLE
No unit indicator initial conditions

### ISSUE THREAD

**Issue by LirryPinter** [nens/threedi-api-qgis-client#66]
* threedi-api-qgis-client version: 1.5.0b
* Python version: ?
* Operating System: Windows

### Description

There is no unit indicator when defining global values in the initial conditions step

![image](https://user-images.githubusercontent.com/44164164/85267002-efc39600-b474-11ea-9a03-3274ab4cd194.png)

Additionally, the value itself should be on the left.

**Comment by DamnBack** [comment]
Fixed in the version 2.0.0
