### ISSUE TITLE
progress not always showing while simulation is running

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#68]
* threedi-api-qgis-client version: 1.5.0b
* Python version:
* Operating System:
![image](https://user-images.githubusercontent.com/1453159/85292815-c28ade00-b49c-11ea-8338-26c2cec6964b.png)

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by DamnBack** [comment]
Fixed in the version 2.0.0
