### ISSUE TITLE
using predefined not clear to user

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#71]
* threedi-api-qgis-client version:1.5.0.b
* Python version:
* Operating System:

### Description
![image](https://user-images.githubusercontent.com/1453159/85292994-02ea5c00-b49d-11ea-9a27-c96ca842eb19.png)

after selecting predefined, nothing needs to be done. but the box below suggests some input required.

when selecting predefined, the box with global value input should not be there

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by DamnBack** [comment]
Fixed in the version 2.0.0
