### ISSUE TITLE
initial water level 2D global doesn't accept negative? 

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#74]
* threedi-api-qgis-client version:
* Python version:
* Operating System:

### Description

In the netherlands we are a bit below sea level. after entering a - i couldnt enter values anymore
![image](https://user-images.githubusercontent.com/1453159/85293280-6aa0a700-b49d-11ea-98fd-4d28da426a47.png)

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by DamnBack** [comment]
Should be fixed now.
