### ISSUE TITLE
list of breaches max 10?

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#76]
* threedi-api-qgis-client version:
* Python version:
* Operating System:

### Description

the list of breaches is max 10
I have also a model with 3000+ breaches. there this doesn't really work. Let's discuss a solution
for now it seems the standard offset of 10 is being used

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by DamnBack** [comment]
Should be fixed now.
