### ISSUE TITLE
rain intensity preview refers sometimes to the wrong simulation

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#77]
* threedi-api-qgis-client version:
* Python version:
* Operating System:

### Description

![image](https://user-images.githubusercontent.com/1453159/85294399-de8f7f00-b49e-11ea-8fb5-959960da22f3.png)

I chose 2 multplie simulation with rain
one with nr 8 and ione with nr 12
in the image you can see that i selected the one with 8 but the preview shows 12
### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by DamnBack** [comment]
Fixed in the version 2.0.0
