### ISSUE TITLE
after changing a model it is required to press change again to update the panel

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#78]
* threedi-api-qgis-client version:
* Python version:
* Operating System:

### Description
after changing a model it is required to press change again to update the panel 

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.
![image](https://user-images.githubusercontent.com/1453159/85294935-873dde80-b49f-11ea-8029-ca6fd03290a5.png)

see screenshot, this part deosn't update otherwise
### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by DamnBack** [comment]
Should be fixed now.
