### ISSUE TITLE
Dike breach

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#80]
* threedi-api-qgis-client version: 1.5.0b
* Python version:
* Operating System:

### Description
for this I have used the wf demo model which should be also available for lutra now.

Duration in hours = can't fill in with a comma
duration, rename to: duration till max depth

There are no defauls. Let's use defaults, users can adjust if they want to
duration = 0.1 h
initial width = 10 m

there is a standard offset of 10 breaches, so users cannot select all breaches available. can we exapdn that and make it searchable?

to discuss:
shown ID is difficult to relate for the user

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by DamnBack** [comment]
Fixed in the version 2.0.0
