### ISSUE TITLE
Blue link texts in "Upload" modal do not open browser

### ISSUE THREAD

**Issue by LirryPinter** [nens/threedi-api-qgis-client#83]
* threedi-api-qgis-client version: 1.5.1b
* Python version: ? 
* Operating System: Windows

### Description

When opening the upload tab, the blue texts should contain links and open the browser. 
Now they are clickable, but nothing happens. Do you need us to deliver what the links are?

**Comment by LirryPinter** [comment]
These are the links for the respective texts


"Log in to the model database"  https://models.lizard.net
"full documentation for new models" https://docs.3di.lizard.net/d_threedi_versioning.html
"install tortoise hg workbench"  https://tortoisehg.bitbucket.io/download/index.html
"full documentation for existing models" https://docs.3di.lizard.net/d_threedi_versioning.html

**Comment by DamnBack** [comment]
Fixed in the version 2.0.0
