### ISSUE TITLE
When having multiple simulations, the dropdown is cut off at "initiation" step 

### ISSUE THREAD

**Issue by LirryPinter** [nens/threedi-api-qgis-client#84]
* threedi-api-qgis-client version: 1.5.1b
* Python version: ?
* Operating System: Windows

### Description

![image](https://user-images.githubusercontent.com/44164164/85679197-796ba180-b6c9-11ea-9d2c-3a71932e42ab.png)

When choosing a simulation to view in the last "initiation" step, the dropdown is cut off.

**Comment by LirryPinter** [comment]
Additionally, the text next to the checkmark is cut off at the start

**Comment by DamnBack** [comment]
Fixed in the version 2.0.0
