### ISSUE TITLE
when logging in tab needs to be hit 6 times in stead of once to get from username to password field

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#86]
* threedi-api-qgis-client version:
* Python version:
* Operating System:

### Description

when logging in, after typing the username, users usually use tab to get to the next field to fill in the password. in the plugin this is not the next field, when pressing tab, users first go to cancel and all other buttons/fields before getting to the password field.
more user firendly is: first tab after username field is password field

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by DamnBack** [comment]
Fixed in the version 2.0.0
