### ISSUE TITLE
Using tab at log in modal does not work logical [DUPLICATE OF #86]

### ISSUE THREAD

**Issue by LirryPinter** [nens/threedi-api-qgis-client#87]
* threedi-api-qgis-client version: 15.1.2b
* Python version: ?
* Operating System: Windows

### Description

When logging in and the user put in the username, the selected object jumps not to the password (as expected) but to the button beneath. It should be top down, so the user can log in quickly.

**Comment by DamnBack** [comment]
Fixed in the version 2.0.0
