### ISSUE TITLE
logging in can take serious amount of time [enhancement]

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#88]
this can take me five minutes:
![image](https://user-images.githubusercontent.com/1453159/86112517-5de90800-bac8-11ea-81a7-2c29c54d936b.png)

we should look at ways to optimize. it might be because I have access to over 3000 models maybe? do you experience the same?

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by DamnBack** [comment]
@Jonasvsl This is server related issue and it seems that it depends on your current servers workload.

**Comment by Jonasvsl** [comment]
@DamnBack yes in some cases it is possible to have too many models and then it takes forever. we can make it more sustainable by using pagination (only loading the frist 10) and letting users use either apgination or a search bar which uses an api call in the get simulations endpoint with a contains query

**Comment by Jonasvsl** [comment]
an example implementation like this with the extra columns would be sufficient. The styling can be according to how the plugin is now, the example here is purely for the functionality :

![image](https://user-images.githubusercontent.com/1453159/87031717-d1cf9280-c1e3-11ea-8a70-f9c0aaca546e.png)

- A user can search using the API search
- Only the first 10 models are shown (preferably the last 10 added )
- if the user wants to use the pagination he clicks on the arrows to go back and forth between the modellists

**Comment by Jonasvsl** [comment]
from user feedback, extra ciolumns:
repository name, and kastupdated date in international date format, yyyy-mm-dd

**Comment by DamnBack** [comment]
Pagination added. 
![image](https://user-images.githubusercontent.com/11883222/89535659-004a8880-d7f7-11ea-9747-4df7dd102b4e.png)
