### ISSUE TITLE
naming saved states

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#89]
* threedi-api-qgis-client version:
* Python version:
* Operating System:

### Description
when defining a saved state the correct api call is being used. however in the API the name is randomly generated because no name of the saved state is provided. please add the name of the simulation as name for the saved state 

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by DamnBack** [comment]
Fixed in the version 2.0.0
