### ISSUE TITLE
Upload screen: outline last sentence

### ISSUE THREAD

**Issue by LirryPinter** [nens/threedi-api-qgis-client#91]
* threedi-api-qgis-client version:
* Python version:
* Operating System:

### Description

The last sentence is not properly alligned:

![image](https://user-images.githubusercontent.com/44164164/86138309-97346e80-baee-11ea-9ba1-39b32dd5566f.png)

"Full documentation for existing models"

**Comment by DamnBack** [comment]
Fixed in the version 2.0.1
