### ISSUE TITLE
Breaches: "Duration till max depth" doesn't have a field

### ISSUE THREAD

**Issue by LirryPinter** [nens/threedi-api-qgis-client#92]
* threedi-api-qgis-client version:
* Python version:
* Operating System:

### Description

There should be a field to fill in the values, now there is only a number

![image](https://user-images.githubusercontent.com/44164164/86140842-9b15c000-baf1-11ea-9ea4-c15bea632348.png)

**Comment by DamnBack** [comment]
Fixed in 2.0.1.
