### ISSUE TITLE
progress not picking up changes to simulation like stopped

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#94]
after stopping the first two simulations in this example:
![image](https://user-images.githubusercontent.com/1453159/86453385-faf0ae80-bd1d-11ea-8219-a50e40666724.png)

the list is not refreshed with the status of these simulations. To compare the interface of beta.3di.live (here only simulations are shown that are currently running). 

![image](https://user-images.githubusercontent.com/1453159/86453445-1360c900-bd1e-11ea-928f-bfce1572a4e5.png)

Expcted behaviour in the qgis plugin: show status of the progress like crashed, or shutdown.

**Comment by DamnBack** [comment]
Stop status is not reported via websocket. This seems like something to implement on the backend.

**Comment by leendertvanwolfswinkel** [comment]
Or just periodically check the simulation status using ```simulation_api.simulations_status_list(simulation_id).name```?

**Comment by leendertvanwolfswinkel** [comment]
@jpprins1 How would you recommend to handle this?

**Comment by Jonasvsl** [comment]
is this also related to the fact that the progress stays at 0% even though the simulation started or is finished?

**Comment by Jonasvsl** [comment]
topdesk nummer 2211 0108

**Comment by leendertvanwolfswinkel** [comment]
> is this also related to the fact that the progress stays at 0% even though the simulation started or is finished?

Could be, we will have to look into this

**Comment by jpprins1** [comment]
This (kind of) message should be sent over the websocket:
{"type": "status", "data": {"status": "finished", "simulation_id": 25722}}
