### ISSUE TITLE
breaches default values

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#97]
* threedi-api-qgis-client version: 2.0.1
* Python version:
* Operating System:

### Description

please use 0.1 and 10 as default values:
![image](https://user-images.githubusercontent.com/1453159/86455354-c92d1700-bd20-11ea-99bb-aa87acf61259.png)

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by DamnBack** [comment]
Should be fixed in 2.0.2 release.
