### ISSUE TITLE
selecting breaches impossible in some models

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#98]
* threedi-api-qgis-client version: 2.0.1b
* Python version:
* Operating System:

### Description

This list is only scrollable:
![image](https://user-images.githubusercontent.com/1453159/86455433-e5c94f00-bd20-11ea-80fc-5c2bdb6f4bfc.png)
can we change this in also an input field where you can type?

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by leendertvanwolfswinkel** [comment]
Solution would be similar to this:

![image](https://user-images.githubusercontent.com/26224299/125455485-6104399d-9d0e-4a20-be49-02331e45543a.png)

**Comment by ldebek** [comment]
Combobox results can be now filtered by typing.
