### ISSUE TITLE
results download downloads gridadmin of previous used model

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#99]
* threedi-api-qgis-client version: 2.0.1b
* Python version:
* Operating System:

### Description
when using the result download 1 of the files being downloaded is the gridadmin.h5 file.

After changing model in the plugin, and then doing a download the gridadmin.h5 file being downloaded is not the file that belongs to the model that was run but that of the previous used model.

I checked by downloading manually in swagger, comparing files and loading the results in the plugin using the 3di toolbox

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by DamnBack** [comment]
Should be fixed in 2.0.2 release.
